package rum

import (
	"container/list"
	"context"
	"errors"
	"io"
	"math/rand/v2"
	"net/http"
	"strings"
	"sync"
	"time"

	"github.com/gin-gonic/gin"
	"github.com/google/uuid"
	"golang.org/x/time/rate"

	"github.com/mosamlife/wpmgr/apps/api/internal/db/sqlc"
)

// beaconKeyLookup is the subset of BeaconKeyRepo used by the ingest handler.
// Defined as an interface so the handler can be tested without a DB.
type beaconKeyLookup interface {
	LookupBeaconKey(ctx context.Context, keyHash []byte) (sqlc.LookupRumBeaconKeyRow, error)
}

// MaxBeaconBodyBytes is the ingest handler's body cap (8 KiB). Requests larger
// than this are rejected with 413 before any parsing, protecting the server
// from large-body abuse over the unauthenticated ingest endpoint.
const MaxBeaconBodyBytes = 8 * 1024

// Per-metric value ceilings (in milli-units, matching ValueMilli).
// Values above these are clamped to the ceiling and still stored — dropping
// slow-tail samples would bias the p75 the product reports optimistically,
// which is the worst failure mode for a CWV product.
//
// LCP/TTFB/FCP/INP ceilings: 600 000 ms (10 min). Legitimately slow page loads
// on 2G/satellite connections reach tens of seconds; 10 min is far enough past
// any real measurement that it is clearly a sensor fault, but we clamp rather
// than discard so the histogram stays honest.
//
// CLS ceiling: 10 000 milli-units (CLS 10.0). CLS is stored as value*1000
// (e.g. CLS 0.25 → 250); a real tail past CLS 1.0 is common for broken pages;
// 10.0 is astronomically large and anything higher is almost certainly a sensor
// fault, but we clamp rather than drop.
const (
	metricCeilingTimeMS int32 = 600_000 // LCP, FCP, TTFB, INP
	metricCeilingCLS    int32 = 10_000  // CLS (milli-units)
)

// clsMetrics is the set of metrics whose value represents milli-units of CLS
// and therefore uses metricCeilingCLS instead of metricCeilingTimeMS.
var clsMetrics = map[string]bool{"cls": true}

// clampValue enforces per-metric value bounds:
//   - negative → returns (0, false): drop-this-event sentinel (204, not 400).
//   - above ceiling → returns (ceiling, true): store the clamped value.
//   - in range → returns (value, true): store as-is.
func clampValue(metric string, value int32) (clamped int32, ok bool) {
	if value < 0 {
		return 0, false
	}
	ceiling := metricCeilingTimeMS
	if clsMetrics[metric] {
		ceiling = metricCeilingCLS
	}
	if value > ceiling {
		return ceiling, true
	}
	return value, true
}

// beaconBody is the JSON shape expected from the sendBeacon payload.
type beaconBody struct {
	// Key is the plaintext beacon key (base64url-encoded, generated by the CP
	// and passed to the agent). The handler sha256-hashes it before the DB lookup.
	Key string `json:"key"`
	// URL is the full page URL from window.location.href. The handler normalises
	// it to a path pattern and strips query strings + fragments.
	URL string `json:"url"`
	// Metric is one of: lcp | inp | cls | ttfb | fcp.
	Metric string `json:"metric"`
	// Value is the raw metric value in milliseconds (integer).
	Value int32 `json:"value"`
	// Device is one of: desktop | mobile | tablet.
	Device string `json:"device,omitempty"`
	// Country is the ISO-3166-1 alpha-2 code. Optional — the handler falls back
	// to "__other__" when absent or invalid.
	Country string `json:"country,omitempty"`
	// Conn is the connection type: 4g | 3g | 2g | slow-2g | offline | unknown.
	Conn string `json:"conn,omitempty"`
}

// ipLRU is a bounded LRU cache for per-IP rate limiters. The hard cap prevents
// unbounded heap growth on the public ingest endpoint (M1 fix).
type ipLRU struct {
	mu       sync.Mutex
	cap      int
	items    map[string]*list.Element
	order    *list.List // front = most-recently-used
	newLimit func() *rate.Limiter
}

type lruEntry struct {
	ip      string
	limiter *rate.Limiter
}

// newIPLRU constructs a bounded LRU rate-limiter cache.
func newIPLRU(cap int, newLimit func() *rate.Limiter) *ipLRU {
	return &ipLRU{
		cap:      cap,
		items:    make(map[string]*list.Element, cap),
		order:    list.New(),
		newLimit: newLimit,
	}
}

// get returns the limiter for ip, creating one if absent.
// When full, the least-recently-used entry is evicted.
func (c *ipLRU) get(ip string) *rate.Limiter {
	c.mu.Lock()
	defer c.mu.Unlock()

	if el, ok := c.items[ip]; ok {
		c.order.MoveToFront(el)
		return el.Value.(*lruEntry).limiter
	}
	// Evict LRU when at capacity.
	if c.order.Len() >= c.cap {
		back := c.order.Back()
		if back != nil {
			c.order.Remove(back)
			delete(c.items, back.Value.(*lruEntry).ip)
		}
	}
	l := c.newLimit()
	el := c.order.PushFront(&lruEntry{ip: ip, limiter: l})
	c.items[ip] = el
	return l
}

// len returns the current number of tracked IPs (for tests).
func (c *ipLRU) len() int {
	c.mu.Lock()
	defer c.mu.Unlock()
	return c.order.Len()
}

// DefaultIPLimiterCap is the maximum number of distinct client IPs tracked in
// the per-IP rate-limiter LRU. Sized to hold the realistic concurrent-session
// count for a large deployment while keeping the working set well below a
// dangerous memory cliff.
const DefaultIPLimiterCap = 65_536

// Handler serves the public POST /rum/ingest endpoint. It is intentionally NOT
// under /api/v1 or /agent/v1: no session, no signature, no tenant gate. The
// beacon key is the only credential. Handler is registered on the root Gin
// engine via RegisterPublic.
type Handler struct {
	store   Store
	beaconR beaconKeyLookup

	// ipLimiters is a bounded LRU of per-IP token-bucket rate limiters (M1 fix).
	// siteLimiters is naturally bounded by site count — left as a plain map.
	ipLimiters   *ipLRU
	siteLimiters map[uuid.UUID]*rate.Limiter
	mu           sync.Mutex
}

// NewHandler constructs a RUM ingest handler with the default IP-limiter cap.
// beaconR is *BeaconKeyRepo (satisfies beaconKeyLookup).
func NewHandler(store Store, beaconR *BeaconKeyRepo) *Handler {
	return newHandlerWithCap(store, beaconR, DefaultIPLimiterCap)
}

// newHandlerWithCap constructs a RUM ingest handler with a custom IP-limiter cap.
// Used in tests to inject a stub beacon repo and bound the LRU for fast iteration.
func newHandlerWithCap(store Store, beaconR beaconKeyLookup, ipCap int) *Handler {
	return &Handler{
		store:   store,
		beaconR: beaconR,
		ipLimiters: newIPLRU(ipCap, func() *rate.Limiter {
			return rate.NewLimiter(rate.Every(10*time.Millisecond), 200) // 100 r/s, burst 200
		}),
		siteLimiters: make(map[uuid.UUID]*rate.Limiter),
	}
}

// RegisterPublic mounts POST /rum/ingest on the root engine with the minimum
// required middleware (CORS for sendBeacon cross-origin simple requests, body
// cap, rate limiting). No session, no auth, no tenant gate.
func (h *Handler) RegisterPublic(engine interface {
	Group(string, ...gin.HandlerFunc) *gin.RouterGroup
}) {
	g := engine.Group("/rum")
	g.Use(rumCORSMiddleware())
	g.POST("/ingest", h.handleIngest)
	// OPTIONS preflight for browsers that send it despite sendBeacon being a
	// simple request (some browsers do send CORS preflights for POST application/json).
	g.OPTIONS("/ingest", func(c *gin.Context) {
		c.Status(http.StatusNoContent)
	})
}

// handleIngest is the POST /rum/ingest handler.
func (h *Handler) handleIngest(c *gin.Context) {
	// ── Per-IP rate limit (abuse ceiling: 100 req/s per IP, burst 200) ──────
	ip := clientIP(c)
	if !h.ipLimiters.get(ip).Allow() {
		c.Status(http.StatusTooManyRequests)
		return
	}

	// ── Body cap ─────────────────────────────────────────────────────────────
	c.Request.Body = http.MaxBytesReader(c.Writer, c.Request.Body, MaxBeaconBodyBytes)
	var body beaconBody
	if err := c.ShouldBindJSON(&body); err != nil {
		if isBodyTooLarge(err) {
			c.Status(http.StatusRequestEntityTooLarge)
			return
		}
		c.Status(http.StatusBadRequest)
		return
	}

	// ── Metric allow-list ─────────────────────────────────────────────────────
	if !AllowedMetrics[body.Metric] {
		c.Status(http.StatusBadRequest)
		return
	}

	// ── Per-metric value clamping (H1) ────────────────────────────────────────
	// Clamp out-of-range values rather than rejecting them. Dropping slow-tail
	// samples biases the p75 optimistically — the worst failure for a CWV product.
	// Negative values are truly impossible (no real metric is negative) and are
	// silently discarded with 204 (uniform with other discard paths).
	valueMilli, ok := clampValue(body.Metric, body.Value)
	if !ok {
		// Negative: impossible measurement. Discard silently — 204, not 400, so
		// the status code does not act as a behavioral oracle.
		c.Status(http.StatusNoContent)
		return
	}

	// ── Beacon key lookup ─────────────────────────────────────────────────────
	// Hash the presented plaintext key before the DB query. The DB stores only
	// sha256(key); the plaintext is never logged or stored.
	if body.Key == "" {
		c.Status(http.StatusUnauthorized)
		return
	}
	keyHash, err := HashBeaconKeyFromPlaintext(body.Key)
	if err != nil {
		c.Status(http.StatusUnauthorized)
		return
	}
	row, err := h.beaconR.LookupBeaconKey(c.Request.Context(), keyHash)
	if err != nil {
		if errors.Is(err, ErrBeaconKeyNotFound) {
			// Return 204 (not 401) to not leak whether a key exists. The sendBeacon
			// API ignores the response body regardless; 204 is the normal success code.
			c.Status(http.StatusNoContent)
			return
		}
		c.Status(http.StatusInternalServerError)
		return
	}

	// ── RUM enabled check ─────────────────────────────────────────────────────
	if !row.RumEnabled {
		c.Status(http.StatusNoContent) // silently discard
		return
	}

	// ── Per-site rate limit (abuse ceiling: 500 req/s per site, burst 1000) ──
	if !h.siteLimiter(row.SiteID).Allow() {
		c.Status(http.StatusTooManyRequests)
		return
	}

	// ── Server-side unbiased random sampling ─────────────────────────────────
	// Only this shapes the stored distribution. Rate limits (above) are the abuse
	// ceiling and are sized to never fire on real production traffic. Sampling
	// is the sole mechanism for controlling storage volume.
	sampleRate := float64(row.RumSampleRate)
	if sampleRate <= 0 {
		c.Status(http.StatusNoContent)
		return
	}
	if sampleRate < 1.0 && rand.Float64() >= sampleRate {
		// Event is sampled out. Return 204 — the client has already fired and
		// nothing useful can be done with a rejection code.
		c.Status(http.StatusNoContent)
		return
	}

	// ── URL normalization ─────────────────────────────────────────────────────
	urlPattern := NormalizeURL(body.URL)
	if urlPattern == "" {
		urlPattern = "/"
	}

	// ── Normalise device/country/conn with allow-list fallbacks ──────────────
	device := strings.ToLower(body.Device)
	if !AllowedDevices[device] {
		device = "desktop"
	}
	// Origin/Referer header check is a soft, P1-backlog origin validation — it is
	// NOT a security boundary. Origin and Referer are both forgeable by any script
	// on the page or a direct curl, so the beacon key remains the sole access
	// credential. (L1: deliberate design decision, not an oversight.)
	country := NormalizeCountry(body.Country, nil) // Phase 1: no per-site top-N cap
	conn := strings.ToLower(body.Conn)
	if !AllowedConn[conn] {
		conn = "unknown"
	}

	// ── Write event under InRumIngestTx ──────────────────────────────────────
	if err := h.store.WriteEvent(c.Request.Context(), IngestParams{
		TenantID:   row.TenantID,
		SiteID:     row.SiteID,
		URLPattern: urlPattern,
		Metric:     body.Metric,
		ValueMilli: valueMilli,
		Device:     device,
		Country:    country,
		Conn:       conn,
	}); err != nil {
		// Ingest failures are silent to the browser (can't retry a fired beacon).
		// Log on the server side; return 204 so the browser doesn't retry.
		c.Status(http.StatusNoContent)
		return
	}

	c.Status(http.StatusNoContent)
}

// rumCORSMiddleware returns a CORS middleware scoped to the /rum group only.
// sendBeacon fires a POST with application/json — some browsers send a preflight
// OPTIONS; others treat it as a "simple request" (Content-Type is excluded from
// the cors "simple" list for application/json, so preflights DO happen).
// The ACAO header permits the site's own origin; we don't wildcard here because
// the beacon key already scopes access to one site.
func rumCORSMiddleware() gin.HandlerFunc {
	return func(c *gin.Context) {
		// Reflect the request origin (permissive for ingest; the beacon key is
		// the actual access control). Browsers won't send the beacon without this.
		origin := c.Request.Header.Get("Origin")
		if origin == "" {
			origin = "*"
		}
		c.Header("Access-Control-Allow-Origin", origin)
		c.Header("Access-Control-Allow-Methods", "POST, OPTIONS")
		c.Header("Access-Control-Allow-Headers", "Content-Type")
		c.Header("Access-Control-Max-Age", "3600")
		c.Header("Vary", "Origin")
		if c.Request.Method == http.MethodOptions {
			c.AbortWithStatus(http.StatusNoContent)
			return
		}
		c.Next()
	}
}

// siteLimiter returns or creates a per-site token-bucket rate limiter.
// Sized at 500 req/s with burst 1000 — well above real ingest rates.
func (h *Handler) siteLimiter(siteID uuid.UUID) *rate.Limiter {
	h.mu.Lock()
	defer h.mu.Unlock()
	if l, ok := h.siteLimiters[siteID]; ok {
		return l
	}
	l := rate.NewLimiter(rate.Every(2*time.Millisecond), 1000) // 500 r/s, burst 1000
	h.siteLimiters[siteID] = l
	return l
}

// clientIP extracts the trusted client IP.
// Behind the GCP L7 LB the trustworthy client IP is the RIGHTMOST entry
// appended by the LB, not the leftmost (which is client-supplied and spoofable).
// Spoofing the leftmost XFF header with a random value would otherwise allow an
// attacker to obtain a fresh rate-limit bucket on every request, defeating M1.
// (M2 fix: parse from the right instead of the left.)
func clientIP(c *gin.Context) string {
	if xff := c.Request.Header.Get("X-Forwarded-For"); xff != "" {
		// The GCP LB appends exactly one hop. The rightmost token is the entry
		// appended by the trusted proxy; everything to the left may be spoofed.
		parts := strings.Split(xff, ",")
		if ip := strings.TrimSpace(parts[len(parts)-1]); ip != "" {
			return ip
		}
	}
	return c.ClientIP()
}

// isBodyTooLarge returns true when err is the MaxBytesReader overflow error.
func isBodyTooLarge(err error) bool {
	var maxErr *http.MaxBytesError
	return errors.As(err, &maxErr) || (err != nil && err == io.ErrUnexpectedEOF)
}
