// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: files.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const getSiteFileManager = `-- name: GetSiteFileManager :one


SELECT site_id, tenant_id, files_enabled, root_jail, created_at, updated_at FROM site_file_manager
WHERE site_id = $1
`

// m82 File Manager queries. All statements are tenant-scoped both explicitly
// (tenant_id in WHERE/VALUES) and via RLS (app.tenant_id / app.agent GUC).
// The repo wraps each call in InTenantTx — these queries never set GUCs.
// updated_at is set via now() in mutations; there is no trigger.
// ---------------------------------------------------------------------------
// site_file_manager
// ---------------------------------------------------------------------------
func (q *Queries) GetSiteFileManager(ctx context.Context, siteID uuid.UUID) (SiteFileManager, error) {
	row := q.db.QueryRow(ctx, getSiteFileManager, siteID)
	var i SiteFileManager
	err := row.Scan(
		&i.SiteID,
		&i.TenantID,
		&i.FilesEnabled,
		&i.RootJail,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertFileTransfer = `-- name: InsertFileTransfer :exec

INSERT INTO file_transfers (
    id, tenant_id, site_id,
    direction, rel_path, status,
    object_key, size_bytes, chunk_count,
    created_by, expires_at
) VALUES (
    $1, $2, $3,
    $4, $5, $6,
    $7, $8, $9,
    $10, $11
)
`

type InsertFileTransferParams struct {
	ID         uuid.UUID `json:"id"`
	TenantID   uuid.UUID `json:"tenant_id"`
	SiteID     uuid.UUID `json:"site_id"`
	Direction  string    `json:"direction"`
	RelPath    string    `json:"rel_path"`
	Status     string    `json:"status"`
	ObjectKey  string    `json:"object_key"`
	SizeBytes  int64     `json:"size_bytes"`
	ChunkCount int32     `json:"chunk_count"`
	CreatedBy  uuid.UUID `json:"created_by"`
	ExpiresAt  time.Time `json:"expires_at"`
}

// ---------------------------------------------------------------------------
// file_transfers
// ---------------------------------------------------------------------------
func (q *Queries) InsertFileTransfer(ctx context.Context, arg InsertFileTransferParams) error {
	_, err := q.db.Exec(ctx, insertFileTransfer,
		arg.ID,
		arg.TenantID,
		arg.SiteID,
		arg.Direction,
		arg.RelPath,
		arg.Status,
		arg.ObjectKey,
		arg.SizeBytes,
		arg.ChunkCount,
		arg.CreatedBy,
		arg.ExpiresAt,
	)
	return err
}

const listFileTransfers = `-- name: ListFileTransfers :many
SELECT id, tenant_id, site_id, direction, rel_path, status, object_key, size_bytes, chunk_count, created_by, created_at, expires_at FROM file_transfers
WHERE tenant_id = $1
  AND site_id   = $2
ORDER BY created_at DESC, id DESC
LIMIT  $4
OFFSET $3
`

type ListFileTransfersParams struct {
	TenantID  uuid.UUID `json:"tenant_id"`
	SiteID    uuid.UUID `json:"site_id"`
	RowOffset int32     `json:"row_offset"`
	RowLimit  int32     `json:"row_limit"`
}

// Returns the most-recent transfers for a site (newest first).
func (q *Queries) ListFileTransfers(ctx context.Context, arg ListFileTransfersParams) ([]FileTransfer, error) {
	rows, err := q.db.Query(ctx, listFileTransfers,
		arg.TenantID,
		arg.SiteID,
		arg.RowOffset,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FileTransfer
	for rows.Next() {
		var i FileTransfer
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.SiteID,
			&i.Direction,
			&i.RelPath,
			&i.Status,
			&i.ObjectKey,
			&i.SizeBytes,
			&i.ChunkCount,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.ExpiresAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertSiteFileManager = `-- name: UpsertSiteFileManager :exec
INSERT INTO site_file_manager (
    site_id, tenant_id, files_enabled, updated_at
) VALUES (
    $1, $2, $3, now()
) ON CONFLICT (site_id) DO UPDATE SET
    files_enabled = EXCLUDED.files_enabled,
    updated_at    = now()
`

type UpsertSiteFileManagerParams struct {
	SiteID       uuid.UUID `json:"site_id"`
	TenantID     uuid.UUID `json:"tenant_id"`
	FilesEnabled bool      `json:"files_enabled"`
}

// Insert-or-update the per-site file manager flag. tenant_id is always the
// principal's tenant (belt-and-braces alongside the RLS policy).
func (q *Queries) UpsertSiteFileManager(ctx context.Context, arg UpsertSiteFileManagerParams) error {
	_, err := q.db.Exec(ctx, upsertSiteFileManager, arg.SiteID, arg.TenantID, arg.FilesEnabled)
	return err
}
