// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: perf.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const getCacheStats = `-- name: GetCacheStats :one

SELECT site_id, tenant_id, cached_pages_count, cache_size_bytes, last_purged_at, last_purge_kind, last_preload_at, preload_pending, preload_total, reported_at FROM site_cache_stats
WHERE site_id = $1
`

// ---------------------------------------------------------------------------
// site_cache_stats
// ---------------------------------------------------------------------------
func (q *Queries) GetCacheStats(ctx context.Context, siteID uuid.UUID) (SiteCacheStat, error) {
	row := q.db.QueryRow(ctx, getCacheStats, siteID)
	var i SiteCacheStat
	err := row.Scan(
		&i.SiteID,
		&i.TenantID,
		&i.CachedPagesCount,
		&i.CacheSizeBytes,
		&i.LastPurgedAt,
		&i.LastPurgeKind,
		&i.LastPreloadAt,
		&i.PreloadPending,
		&i.PreloadTotal,
		&i.ReportedAt,
	)
	return i, err
}

const getPerfConfig = `-- name: GetPerfConfig :one


SELECT site_id, tenant_id, cache_enabled, cache_logged_in, cache_mobile, cache_refresh, cache_refresh_interval, cache_link_prefetch, cache_bypass_urls, cache_bypass_cookies, cache_include_queries, cache_include_cookies, css_js_minify, css_rucss, css_rucss_include_selectors, css_js_self_host_third_party, js_delay, js_delay_method, js_delay_excludes, js_delay_third_party, js_delay_third_party_excludes, fonts_display_swap, fonts_optimize_google, fonts_preload, lazy_load, lazy_load_exclusions, properly_size_images, youtube_placeholder, self_host_gravatars, cdn_enabled, cdn_url, cdn_file_types, cdn_provider, cdn_credentials_encrypted, db_auto_clean, db_auto_clean_interval, db_post_revisions, db_post_auto_drafts, db_post_trashed, db_comments_spam, db_comments_trashed, db_transients_expired, db_optimize_tables, bloat_disable_block_css, bloat_disable_dashicons, bloat_disable_emojis, bloat_disable_jquery_migrate, bloat_disable_xml_rpc, bloat_disable_rss_feed, bloat_disable_oembeds, bloat_heartbeat_control, bloat_post_revisions_control, server_software, dropin_installed, wp_cache_constant_set, htaccess_managed, config_version, created_at, updated_at FROM site_perf_config
WHERE site_id = $1
`

// M36 Performance Suite queries (ADR-046). Every statement is tenant-scoped both
// explicitly (tenant_id in the WHERE/VALUES) and by RLS (the app.tenant_id
// policy / app.agent policy). The repo wraps each call in InTenantTx/InAgentTx —
// these queries never set GUCs themselves. updated_at is set here via now().
// ---------------------------------------------------------------------------
// site_perf_config
// ---------------------------------------------------------------------------
func (q *Queries) GetPerfConfig(ctx context.Context, siteID uuid.UUID) (SitePerfConfig, error) {
	row := q.db.QueryRow(ctx, getPerfConfig, siteID)
	var i SitePerfConfig
	err := row.Scan(
		&i.SiteID,
		&i.TenantID,
		&i.CacheEnabled,
		&i.CacheLoggedIn,
		&i.CacheMobile,
		&i.CacheRefresh,
		&i.CacheRefreshInterval,
		&i.CacheLinkPrefetch,
		&i.CacheBypassUrls,
		&i.CacheBypassCookies,
		&i.CacheIncludeQueries,
		&i.CacheIncludeCookies,
		&i.CssJsMinify,
		&i.CssRucss,
		&i.CssRucssIncludeSelectors,
		&i.CssJsSelfHostThirdParty,
		&i.JsDelay,
		&i.JsDelayMethod,
		&i.JsDelayExcludes,
		&i.JsDelayThirdParty,
		&i.JsDelayThirdPartyExcludes,
		&i.FontsDisplaySwap,
		&i.FontsOptimizeGoogle,
		&i.FontsPreload,
		&i.LazyLoad,
		&i.LazyLoadExclusions,
		&i.ProperlySizeImages,
		&i.YoutubePlaceholder,
		&i.SelfHostGravatars,
		&i.CdnEnabled,
		&i.CdnUrl,
		&i.CdnFileTypes,
		&i.CdnProvider,
		&i.CdnCredentialsEncrypted,
		&i.DbAutoClean,
		&i.DbAutoCleanInterval,
		&i.DbPostRevisions,
		&i.DbPostAutoDrafts,
		&i.DbPostTrashed,
		&i.DbCommentsSpam,
		&i.DbCommentsTrashed,
		&i.DbTransientsExpired,
		&i.DbOptimizeTables,
		&i.BloatDisableBlockCss,
		&i.BloatDisableDashicons,
		&i.BloatDisableEmojis,
		&i.BloatDisableJqueryMigrate,
		&i.BloatDisableXmlRpc,
		&i.BloatDisableRssFeed,
		&i.BloatDisableOembeds,
		&i.BloatHeartbeatControl,
		&i.BloatPostRevisionsControl,
		&i.ServerSoftware,
		&i.DropinInstalled,
		&i.WpCacheConstantSet,
		&i.HtaccessManaged,
		&i.ConfigVersion,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getRucssJob = `-- name: GetRucssJob :one
SELECT id, tenant_id, site_id, structure_hash, url, state, error_reason, result_id, created_at, completed_at FROM rucss_jobs
WHERE id = $1 AND tenant_id = $2
`

type GetRucssJobParams struct {
	ID       string    `json:"id"`
	TenantID uuid.UUID `json:"tenant_id"`
}

func (q *Queries) GetRucssJob(ctx context.Context, arg GetRucssJobParams) (RucssJob, error) {
	row := q.db.QueryRow(ctx, getRucssJob, arg.ID, arg.TenantID)
	var i RucssJob
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.SiteID,
		&i.StructureHash,
		&i.Url,
		&i.State,
		&i.ErrorReason,
		&i.ResultID,
		&i.CreatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const getRucssResultByHash = `-- name: GetRucssResultByHash :one

SELECT id, tenant_id, site_id, structure_hash, url, original_css_bytes, used_css_bytes, reduction_pct, used_css_s3_key, selectors_total, selectors_kept, selectors_dropped, compute_ms, created_at, last_used_at FROM rucss_results
WHERE site_id = $1 AND structure_hash = $2
`

type GetRucssResultByHashParams struct {
	SiteID        uuid.UUID `json:"site_id"`
	StructureHash string    `json:"structure_hash"`
}

// ---------------------------------------------------------------------------
// rucss_results
// ---------------------------------------------------------------------------
func (q *Queries) GetRucssResultByHash(ctx context.Context, arg GetRucssResultByHashParams) (RucssResult, error) {
	row := q.db.QueryRow(ctx, getRucssResultByHash, arg.SiteID, arg.StructureHash)
	var i RucssResult
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.SiteID,
		&i.StructureHash,
		&i.Url,
		&i.OriginalCssBytes,
		&i.UsedCssBytes,
		&i.ReductionPct,
		&i.UsedCssS3Key,
		&i.SelectorsTotal,
		&i.SelectorsKept,
		&i.SelectorsDropped,
		&i.ComputeMs,
		&i.CreatedAt,
		&i.LastUsedAt,
	)
	return i, err
}

const insertCachePurgeAudit = `-- name: InsertCachePurgeAudit :one

INSERT INTO cache_purge_audit (
    tenant_id, site_id, kind, initiator_user_id, target_urls, urls_count
) VALUES (
    $1, $2, $3, $4, $5, $6
)
RETURNING id, tenant_id, site_id, kind, initiator_user_id, target_urls, urls_count, created_at
`

type InsertCachePurgeAuditParams struct {
	TenantID        uuid.UUID   `json:"tenant_id"`
	SiteID          uuid.UUID   `json:"site_id"`
	Kind            string      `json:"kind"`
	InitiatorUserID pgtype.UUID `json:"initiator_user_id"`
	TargetUrls      []string    `json:"target_urls"`
	UrlsCount       int32       `json:"urls_count"`
}

// ---------------------------------------------------------------------------
// cache_purge_audit
// ---------------------------------------------------------------------------
func (q *Queries) InsertCachePurgeAudit(ctx context.Context, arg InsertCachePurgeAuditParams) (CachePurgeAudit, error) {
	row := q.db.QueryRow(ctx, insertCachePurgeAudit,
		arg.TenantID,
		arg.SiteID,
		arg.Kind,
		arg.InitiatorUserID,
		arg.TargetUrls,
		arg.UrlsCount,
	)
	var i CachePurgeAudit
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.SiteID,
		&i.Kind,
		&i.InitiatorUserID,
		&i.TargetUrls,
		&i.UrlsCount,
		&i.CreatedAt,
	)
	return i, err
}

const insertRucssJob = `-- name: InsertRucssJob :one

INSERT INTO rucss_jobs (
    id, tenant_id, site_id, structure_hash, url, state
) VALUES (
    $1, $2, $3, $4, $5, 'queued'
)
RETURNING id, tenant_id, site_id, structure_hash, url, state, error_reason, result_id, created_at, completed_at
`

type InsertRucssJobParams struct {
	ID            string    `json:"id"`
	TenantID      uuid.UUID `json:"tenant_id"`
	SiteID        uuid.UUID `json:"site_id"`
	StructureHash *string   `json:"structure_hash"`
	Url           *string   `json:"url"`
}

// ---------------------------------------------------------------------------
// rucss_jobs
// ---------------------------------------------------------------------------
func (q *Queries) InsertRucssJob(ctx context.Context, arg InsertRucssJobParams) (RucssJob, error) {
	row := q.db.QueryRow(ctx, insertRucssJob,
		arg.ID,
		arg.TenantID,
		arg.SiteID,
		arg.StructureHash,
		arg.Url,
	)
	var i RucssJob
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.SiteID,
		&i.StructureHash,
		&i.Url,
		&i.State,
		&i.ErrorReason,
		&i.ResultID,
		&i.CreatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const listCachePurgeAuditForSite = `-- name: ListCachePurgeAuditForSite :many
SELECT id, tenant_id, site_id, kind, initiator_user_id, target_urls, urls_count, created_at FROM cache_purge_audit
WHERE tenant_id = $1 AND site_id = $2
ORDER BY created_at DESC, id DESC
LIMIT $4 OFFSET $3
`

type ListCachePurgeAuditForSiteParams struct {
	TenantID  uuid.UUID `json:"tenant_id"`
	SiteID    uuid.UUID `json:"site_id"`
	RowOffset int32     `json:"row_offset"`
	RowLimit  int32     `json:"row_limit"`
}

func (q *Queries) ListCachePurgeAuditForSite(ctx context.Context, arg ListCachePurgeAuditForSiteParams) ([]CachePurgeAudit, error) {
	rows, err := q.db.Query(ctx, listCachePurgeAuditForSite,
		arg.TenantID,
		arg.SiteID,
		arg.RowOffset,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CachePurgeAudit
	for rows.Next() {
		var i CachePurgeAudit
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.SiteID,
			&i.Kind,
			&i.InitiatorUserID,
			&i.TargetUrls,
			&i.UrlsCount,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRucssResultsForSite = `-- name: ListRucssResultsForSite :many
SELECT id, tenant_id, site_id, structure_hash, url, original_css_bytes, used_css_bytes, reduction_pct, used_css_s3_key, selectors_total, selectors_kept, selectors_dropped, compute_ms, created_at, last_used_at FROM rucss_results
WHERE tenant_id = $1 AND site_id = $2
ORDER BY last_used_at DESC, id DESC
LIMIT $4 OFFSET $3
`

type ListRucssResultsForSiteParams struct {
	TenantID  uuid.UUID `json:"tenant_id"`
	SiteID    uuid.UUID `json:"site_id"`
	RowOffset int32     `json:"row_offset"`
	RowLimit  int32     `json:"row_limit"`
}

func (q *Queries) ListRucssResultsForSite(ctx context.Context, arg ListRucssResultsForSiteParams) ([]RucssResult, error) {
	rows, err := q.db.Query(ctx, listRucssResultsForSite,
		arg.TenantID,
		arg.SiteID,
		arg.RowOffset,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RucssResult
	for rows.Next() {
		var i RucssResult
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.SiteID,
			&i.StructureHash,
			&i.Url,
			&i.OriginalCssBytes,
			&i.UsedCssBytes,
			&i.ReductionPct,
			&i.UsedCssS3Key,
			&i.SelectorsTotal,
			&i.SelectorsKept,
			&i.SelectorsDropped,
			&i.ComputeMs,
			&i.CreatedAt,
			&i.LastUsedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const touchRucssResultLastUsed = `-- name: TouchRucssResultLastUsed :exec
UPDATE rucss_results
SET last_used_at = now()
WHERE site_id = $1 AND structure_hash = $2
`

type TouchRucssResultLastUsedParams struct {
	SiteID        uuid.UUID `json:"site_id"`
	StructureHash string    `json:"structure_hash"`
}

func (q *Queries) TouchRucssResultLastUsed(ctx context.Context, arg TouchRucssResultLastUsedParams) error {
	_, err := q.db.Exec(ctx, touchRucssResultLastUsed, arg.SiteID, arg.StructureHash)
	return err
}

const updatePerfInstallState = `-- name: UpdatePerfInstallState :one
UPDATE site_perf_config
SET server_software       = $1,
    dropin_installed      = $2,
    wp_cache_constant_set = $3,
    htaccess_managed      = $4,
    updated_at            = now()
WHERE site_id = $5
RETURNING site_id, tenant_id, cache_enabled, cache_logged_in, cache_mobile, cache_refresh, cache_refresh_interval, cache_link_prefetch, cache_bypass_urls, cache_bypass_cookies, cache_include_queries, cache_include_cookies, css_js_minify, css_rucss, css_rucss_include_selectors, css_js_self_host_third_party, js_delay, js_delay_method, js_delay_excludes, js_delay_third_party, js_delay_third_party_excludes, fonts_display_swap, fonts_optimize_google, fonts_preload, lazy_load, lazy_load_exclusions, properly_size_images, youtube_placeholder, self_host_gravatars, cdn_enabled, cdn_url, cdn_file_types, cdn_provider, cdn_credentials_encrypted, db_auto_clean, db_auto_clean_interval, db_post_revisions, db_post_auto_drafts, db_post_trashed, db_comments_spam, db_comments_trashed, db_transients_expired, db_optimize_tables, bloat_disable_block_css, bloat_disable_dashicons, bloat_disable_emojis, bloat_disable_jquery_migrate, bloat_disable_xml_rpc, bloat_disable_rss_feed, bloat_disable_oembeds, bloat_heartbeat_control, bloat_post_revisions_control, server_software, dropin_installed, wp_cache_constant_set, htaccess_managed, config_version, created_at, updated_at
`

type UpdatePerfInstallStateParams struct {
	ServerSoftware     *string   `json:"server_software"`
	DropinInstalled    bool      `json:"dropin_installed"`
	WpCacheConstantSet bool      `json:"wp_cache_constant_set"`
	HtaccessManaged    bool      `json:"htaccess_managed"`
	SiteID             uuid.UUID `json:"site_id"`
}

// The agent reports the server/install state it observed when applying config.
// Kept separate from UpsertPerfConfig so an operator's config save never
// overwrites agent-reported facts (and vice-versa). Runs under app.agent.
func (q *Queries) UpdatePerfInstallState(ctx context.Context, arg UpdatePerfInstallStateParams) (SitePerfConfig, error) {
	row := q.db.QueryRow(ctx, updatePerfInstallState,
		arg.ServerSoftware,
		arg.DropinInstalled,
		arg.WpCacheConstantSet,
		arg.HtaccessManaged,
		arg.SiteID,
	)
	var i SitePerfConfig
	err := row.Scan(
		&i.SiteID,
		&i.TenantID,
		&i.CacheEnabled,
		&i.CacheLoggedIn,
		&i.CacheMobile,
		&i.CacheRefresh,
		&i.CacheRefreshInterval,
		&i.CacheLinkPrefetch,
		&i.CacheBypassUrls,
		&i.CacheBypassCookies,
		&i.CacheIncludeQueries,
		&i.CacheIncludeCookies,
		&i.CssJsMinify,
		&i.CssRucss,
		&i.CssRucssIncludeSelectors,
		&i.CssJsSelfHostThirdParty,
		&i.JsDelay,
		&i.JsDelayMethod,
		&i.JsDelayExcludes,
		&i.JsDelayThirdParty,
		&i.JsDelayThirdPartyExcludes,
		&i.FontsDisplaySwap,
		&i.FontsOptimizeGoogle,
		&i.FontsPreload,
		&i.LazyLoad,
		&i.LazyLoadExclusions,
		&i.ProperlySizeImages,
		&i.YoutubePlaceholder,
		&i.SelfHostGravatars,
		&i.CdnEnabled,
		&i.CdnUrl,
		&i.CdnFileTypes,
		&i.CdnProvider,
		&i.CdnCredentialsEncrypted,
		&i.DbAutoClean,
		&i.DbAutoCleanInterval,
		&i.DbPostRevisions,
		&i.DbPostAutoDrafts,
		&i.DbPostTrashed,
		&i.DbCommentsSpam,
		&i.DbCommentsTrashed,
		&i.DbTransientsExpired,
		&i.DbOptimizeTables,
		&i.BloatDisableBlockCss,
		&i.BloatDisableDashicons,
		&i.BloatDisableEmojis,
		&i.BloatDisableJqueryMigrate,
		&i.BloatDisableXmlRpc,
		&i.BloatDisableRssFeed,
		&i.BloatDisableOembeds,
		&i.BloatHeartbeatControl,
		&i.BloatPostRevisionsControl,
		&i.ServerSoftware,
		&i.DropinInstalled,
		&i.WpCacheConstantSet,
		&i.HtaccessManaged,
		&i.ConfigVersion,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateRucssJobState = `-- name: UpdateRucssJobState :one
UPDATE rucss_jobs
SET state        = $1,
    error_reason = $2,
    result_id    = $3,
    completed_at = CASE WHEN $4::boolean THEN now() ELSE completed_at END
WHERE id = $5 AND tenant_id = $6
RETURNING id, tenant_id, site_id, structure_hash, url, state, error_reason, result_id, created_at, completed_at
`

type UpdateRucssJobStateParams struct {
	State       string      `json:"state"`
	ErrorReason *string     `json:"error_reason"`
	ResultID    pgtype.UUID `json:"result_id"`
	Done        bool        `json:"done"`
	ID          string      `json:"id"`
	TenantID    uuid.UUID   `json:"tenant_id"`
}

// Advance the job lifecycle (queued->running->done|failed). completed_at is set
// (to now()) only when @done is true; result_id/error_reason are passed through
// as the terminal state dictates.
func (q *Queries) UpdateRucssJobState(ctx context.Context, arg UpdateRucssJobStateParams) (RucssJob, error) {
	row := q.db.QueryRow(ctx, updateRucssJobState,
		arg.State,
		arg.ErrorReason,
		arg.ResultID,
		arg.Done,
		arg.ID,
		arg.TenantID,
	)
	var i RucssJob
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.SiteID,
		&i.StructureHash,
		&i.Url,
		&i.State,
		&i.ErrorReason,
		&i.ResultID,
		&i.CreatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const upsertCacheStats = `-- name: UpsertCacheStats :one
INSERT INTO site_cache_stats (
    site_id, tenant_id, cached_pages_count, cache_size_bytes,
    last_purged_at, last_purge_kind, last_preload_at,
    preload_pending, preload_total, reported_at
) VALUES (
    $1, $2, $3, $4,
    $5, $6, $7,
    $8, $9, now()
)
ON CONFLICT (site_id) DO UPDATE SET
    cached_pages_count = EXCLUDED.cached_pages_count,
    cache_size_bytes   = EXCLUDED.cache_size_bytes,
    last_purged_at     = EXCLUDED.last_purged_at,
    last_purge_kind    = EXCLUDED.last_purge_kind,
    last_preload_at    = EXCLUDED.last_preload_at,
    preload_pending    = EXCLUDED.preload_pending,
    preload_total      = EXCLUDED.preload_total,
    reported_at        = now()
RETURNING site_id, tenant_id, cached_pages_count, cache_size_bytes, last_purged_at, last_purge_kind, last_preload_at, preload_pending, preload_total, reported_at
`

type UpsertCacheStatsParams struct {
	SiteID           uuid.UUID          `json:"site_id"`
	TenantID         uuid.UUID          `json:"tenant_id"`
	CachedPagesCount int32              `json:"cached_pages_count"`
	CacheSizeBytes   int64              `json:"cache_size_bytes"`
	LastPurgedAt     pgtype.Timestamptz `json:"last_purged_at"`
	LastPurgeKind    *string            `json:"last_purge_kind"`
	LastPreloadAt    pgtype.Timestamptz `json:"last_preload_at"`
	PreloadPending   int32              `json:"preload_pending"`
	PreloadTotal     int32              `json:"preload_total"`
}

// The agent pushes the latest cache gauges; overwritten in place (no history).
func (q *Queries) UpsertCacheStats(ctx context.Context, arg UpsertCacheStatsParams) (SiteCacheStat, error) {
	row := q.db.QueryRow(ctx, upsertCacheStats,
		arg.SiteID,
		arg.TenantID,
		arg.CachedPagesCount,
		arg.CacheSizeBytes,
		arg.LastPurgedAt,
		arg.LastPurgeKind,
		arg.LastPreloadAt,
		arg.PreloadPending,
		arg.PreloadTotal,
	)
	var i SiteCacheStat
	err := row.Scan(
		&i.SiteID,
		&i.TenantID,
		&i.CachedPagesCount,
		&i.CacheSizeBytes,
		&i.LastPurgedAt,
		&i.LastPurgeKind,
		&i.LastPreloadAt,
		&i.PreloadPending,
		&i.PreloadTotal,
		&i.ReportedAt,
	)
	return i, err
}

const upsertPerfConfig = `-- name: UpsertPerfConfig :one
INSERT INTO site_perf_config (
    site_id, tenant_id,
    cache_enabled, cache_logged_in, cache_mobile, cache_refresh,
    cache_refresh_interval, cache_link_prefetch,
    cache_bypass_urls, cache_bypass_cookies, cache_include_queries, cache_include_cookies,
    css_js_minify, css_rucss, css_rucss_include_selectors, css_js_self_host_third_party,
    js_delay, js_delay_method, js_delay_excludes,
    js_delay_third_party, js_delay_third_party_excludes,
    fonts_display_swap, fonts_optimize_google, fonts_preload,
    lazy_load, lazy_load_exclusions, properly_size_images,
    youtube_placeholder, self_host_gravatars,
    cdn_enabled, cdn_url, cdn_file_types, cdn_provider, cdn_credentials_encrypted,
    db_auto_clean, db_auto_clean_interval,
    db_post_revisions, db_post_auto_drafts, db_post_trashed,
    db_comments_spam, db_comments_trashed, db_transients_expired, db_optimize_tables,
    bloat_disable_block_css, bloat_disable_dashicons, bloat_disable_emojis,
    bloat_disable_jquery_migrate, bloat_disable_xml_rpc, bloat_disable_rss_feed,
    bloat_disable_oembeds, bloat_heartbeat_control, bloat_post_revisions_control,
    config_version, updated_at
) VALUES (
    $1, $2,
    $3, $4, $5, $6,
    $7, $8,
    $9, $10, $11, $12,
    $13, $14, $15, $16,
    $17, $18, $19,
    $20, $21,
    $22, $23, $24,
    $25, $26, $27,
    $28, $29,
    $30, $31, $32, $33, $34,
    $35, $36,
    $37, $38, $39,
    $40, $41, $42, $43,
    $44, $45, $46,
    $47, $48, $49,
    $50, $51, $52,
    $53, now()
)
ON CONFLICT (site_id) DO UPDATE SET
    cache_enabled                 = EXCLUDED.cache_enabled,
    cache_logged_in               = EXCLUDED.cache_logged_in,
    cache_mobile                  = EXCLUDED.cache_mobile,
    cache_refresh                 = EXCLUDED.cache_refresh,
    cache_refresh_interval        = EXCLUDED.cache_refresh_interval,
    cache_link_prefetch           = EXCLUDED.cache_link_prefetch,
    cache_bypass_urls             = EXCLUDED.cache_bypass_urls,
    cache_bypass_cookies          = EXCLUDED.cache_bypass_cookies,
    cache_include_queries         = EXCLUDED.cache_include_queries,
    cache_include_cookies         = EXCLUDED.cache_include_cookies,
    css_js_minify                 = EXCLUDED.css_js_minify,
    css_rucss                     = EXCLUDED.css_rucss,
    css_rucss_include_selectors   = EXCLUDED.css_rucss_include_selectors,
    css_js_self_host_third_party  = EXCLUDED.css_js_self_host_third_party,
    js_delay                      = EXCLUDED.js_delay,
    js_delay_method               = EXCLUDED.js_delay_method,
    js_delay_excludes             = EXCLUDED.js_delay_excludes,
    js_delay_third_party          = EXCLUDED.js_delay_third_party,
    js_delay_third_party_excludes = EXCLUDED.js_delay_third_party_excludes,
    fonts_display_swap            = EXCLUDED.fonts_display_swap,
    fonts_optimize_google         = EXCLUDED.fonts_optimize_google,
    fonts_preload                 = EXCLUDED.fonts_preload,
    lazy_load                     = EXCLUDED.lazy_load,
    lazy_load_exclusions          = EXCLUDED.lazy_load_exclusions,
    properly_size_images          = EXCLUDED.properly_size_images,
    youtube_placeholder           = EXCLUDED.youtube_placeholder,
    self_host_gravatars           = EXCLUDED.self_host_gravatars,
    cdn_enabled                   = EXCLUDED.cdn_enabled,
    cdn_url                       = EXCLUDED.cdn_url,
    cdn_file_types                = EXCLUDED.cdn_file_types,
    cdn_provider                  = EXCLUDED.cdn_provider,
    cdn_credentials_encrypted     = EXCLUDED.cdn_credentials_encrypted,
    db_auto_clean                 = EXCLUDED.db_auto_clean,
    db_auto_clean_interval        = EXCLUDED.db_auto_clean_interval,
    db_post_revisions             = EXCLUDED.db_post_revisions,
    db_post_auto_drafts           = EXCLUDED.db_post_auto_drafts,
    db_post_trashed               = EXCLUDED.db_post_trashed,
    db_comments_spam              = EXCLUDED.db_comments_spam,
    db_comments_trashed           = EXCLUDED.db_comments_trashed,
    db_transients_expired         = EXCLUDED.db_transients_expired,
    db_optimize_tables            = EXCLUDED.db_optimize_tables,
    bloat_disable_block_css       = EXCLUDED.bloat_disable_block_css,
    bloat_disable_dashicons       = EXCLUDED.bloat_disable_dashicons,
    bloat_disable_emojis          = EXCLUDED.bloat_disable_emojis,
    bloat_disable_jquery_migrate  = EXCLUDED.bloat_disable_jquery_migrate,
    bloat_disable_xml_rpc         = EXCLUDED.bloat_disable_xml_rpc,
    bloat_disable_rss_feed        = EXCLUDED.bloat_disable_rss_feed,
    bloat_disable_oembeds         = EXCLUDED.bloat_disable_oembeds,
    bloat_heartbeat_control       = EXCLUDED.bloat_heartbeat_control,
    bloat_post_revisions_control  = EXCLUDED.bloat_post_revisions_control,
    config_version                = EXCLUDED.config_version,
    updated_at                    = now()
RETURNING site_id, tenant_id, cache_enabled, cache_logged_in, cache_mobile, cache_refresh, cache_refresh_interval, cache_link_prefetch, cache_bypass_urls, cache_bypass_cookies, cache_include_queries, cache_include_cookies, css_js_minify, css_rucss, css_rucss_include_selectors, css_js_self_host_third_party, js_delay, js_delay_method, js_delay_excludes, js_delay_third_party, js_delay_third_party_excludes, fonts_display_swap, fonts_optimize_google, fonts_preload, lazy_load, lazy_load_exclusions, properly_size_images, youtube_placeholder, self_host_gravatars, cdn_enabled, cdn_url, cdn_file_types, cdn_provider, cdn_credentials_encrypted, db_auto_clean, db_auto_clean_interval, db_post_revisions, db_post_auto_drafts, db_post_trashed, db_comments_spam, db_comments_trashed, db_transients_expired, db_optimize_tables, bloat_disable_block_css, bloat_disable_dashicons, bloat_disable_emojis, bloat_disable_jquery_migrate, bloat_disable_xml_rpc, bloat_disable_rss_feed, bloat_disable_oembeds, bloat_heartbeat_control, bloat_post_revisions_control, server_software, dropin_installed, wp_cache_constant_set, htaccess_managed, config_version, created_at, updated_at
`

type UpsertPerfConfigParams struct {
	SiteID                    uuid.UUID `json:"site_id"`
	TenantID                  uuid.UUID `json:"tenant_id"`
	CacheEnabled              bool      `json:"cache_enabled"`
	CacheLoggedIn             bool      `json:"cache_logged_in"`
	CacheMobile               bool      `json:"cache_mobile"`
	CacheRefresh              bool      `json:"cache_refresh"`
	CacheRefreshInterval      string    `json:"cache_refresh_interval"`
	CacheLinkPrefetch         bool      `json:"cache_link_prefetch"`
	CacheBypassUrls           []string  `json:"cache_bypass_urls"`
	CacheBypassCookies        []string  `json:"cache_bypass_cookies"`
	CacheIncludeQueries       []string  `json:"cache_include_queries"`
	CacheIncludeCookies       []string  `json:"cache_include_cookies"`
	CssJsMinify               bool      `json:"css_js_minify"`
	CssRucss                  bool      `json:"css_rucss"`
	CssRucssIncludeSelectors  []string  `json:"css_rucss_include_selectors"`
	CssJsSelfHostThirdParty   bool      `json:"css_js_self_host_third_party"`
	JsDelay                   bool      `json:"js_delay"`
	JsDelayMethod             string    `json:"js_delay_method"`
	JsDelayExcludes           []string  `json:"js_delay_excludes"`
	JsDelayThirdParty         bool      `json:"js_delay_third_party"`
	JsDelayThirdPartyExcludes []string  `json:"js_delay_third_party_excludes"`
	FontsDisplaySwap          bool      `json:"fonts_display_swap"`
	FontsOptimizeGoogle       bool      `json:"fonts_optimize_google"`
	FontsPreload              bool      `json:"fonts_preload"`
	LazyLoad                  bool      `json:"lazy_load"`
	LazyLoadExclusions        []string  `json:"lazy_load_exclusions"`
	ProperlySizeImages        bool      `json:"properly_size_images"`
	YoutubePlaceholder        bool      `json:"youtube_placeholder"`
	SelfHostGravatars         bool      `json:"self_host_gravatars"`
	CdnEnabled                bool      `json:"cdn_enabled"`
	CdnUrl                    *string   `json:"cdn_url"`
	CdnFileTypes              string    `json:"cdn_file_types"`
	CdnProvider               *string   `json:"cdn_provider"`
	CdnCredentialsEncrypted   []byte    `json:"cdn_credentials_encrypted"`
	DbAutoClean               bool      `json:"db_auto_clean"`
	DbAutoCleanInterval       string    `json:"db_auto_clean_interval"`
	DbPostRevisions           bool      `json:"db_post_revisions"`
	DbPostAutoDrafts          bool      `json:"db_post_auto_drafts"`
	DbPostTrashed             bool      `json:"db_post_trashed"`
	DbCommentsSpam            bool      `json:"db_comments_spam"`
	DbCommentsTrashed         bool      `json:"db_comments_trashed"`
	DbTransientsExpired       bool      `json:"db_transients_expired"`
	DbOptimizeTables          bool      `json:"db_optimize_tables"`
	BloatDisableBlockCss      bool      `json:"bloat_disable_block_css"`
	BloatDisableDashicons     bool      `json:"bloat_disable_dashicons"`
	BloatDisableEmojis        bool      `json:"bloat_disable_emojis"`
	BloatDisableJqueryMigrate bool      `json:"bloat_disable_jquery_migrate"`
	BloatDisableXmlRpc        bool      `json:"bloat_disable_xml_rpc"`
	BloatDisableRssFeed       bool      `json:"bloat_disable_rss_feed"`
	BloatDisableOembeds       bool      `json:"bloat_disable_oembeds"`
	BloatHeartbeatControl     bool      `json:"bloat_heartbeat_control"`
	BloatPostRevisionsControl bool      `json:"bloat_post_revisions_control"`
	ConfigVersion             int32     `json:"config_version"`
}

// Insert-or-update the per-site performance config. The agent install-state
// columns (server_software, dropin_installed, wp_cache_constant_set,
// htaccess_managed) are NOT touched here — those are reported by the agent via
// UpdatePerfInstallState — so an operator config save never clobbers them.
func (q *Queries) UpsertPerfConfig(ctx context.Context, arg UpsertPerfConfigParams) (SitePerfConfig, error) {
	row := q.db.QueryRow(ctx, upsertPerfConfig,
		arg.SiteID,
		arg.TenantID,
		arg.CacheEnabled,
		arg.CacheLoggedIn,
		arg.CacheMobile,
		arg.CacheRefresh,
		arg.CacheRefreshInterval,
		arg.CacheLinkPrefetch,
		arg.CacheBypassUrls,
		arg.CacheBypassCookies,
		arg.CacheIncludeQueries,
		arg.CacheIncludeCookies,
		arg.CssJsMinify,
		arg.CssRucss,
		arg.CssRucssIncludeSelectors,
		arg.CssJsSelfHostThirdParty,
		arg.JsDelay,
		arg.JsDelayMethod,
		arg.JsDelayExcludes,
		arg.JsDelayThirdParty,
		arg.JsDelayThirdPartyExcludes,
		arg.FontsDisplaySwap,
		arg.FontsOptimizeGoogle,
		arg.FontsPreload,
		arg.LazyLoad,
		arg.LazyLoadExclusions,
		arg.ProperlySizeImages,
		arg.YoutubePlaceholder,
		arg.SelfHostGravatars,
		arg.CdnEnabled,
		arg.CdnUrl,
		arg.CdnFileTypes,
		arg.CdnProvider,
		arg.CdnCredentialsEncrypted,
		arg.DbAutoClean,
		arg.DbAutoCleanInterval,
		arg.DbPostRevisions,
		arg.DbPostAutoDrafts,
		arg.DbPostTrashed,
		arg.DbCommentsSpam,
		arg.DbCommentsTrashed,
		arg.DbTransientsExpired,
		arg.DbOptimizeTables,
		arg.BloatDisableBlockCss,
		arg.BloatDisableDashicons,
		arg.BloatDisableEmojis,
		arg.BloatDisableJqueryMigrate,
		arg.BloatDisableXmlRpc,
		arg.BloatDisableRssFeed,
		arg.BloatDisableOembeds,
		arg.BloatHeartbeatControl,
		arg.BloatPostRevisionsControl,
		arg.ConfigVersion,
	)
	var i SitePerfConfig
	err := row.Scan(
		&i.SiteID,
		&i.TenantID,
		&i.CacheEnabled,
		&i.CacheLoggedIn,
		&i.CacheMobile,
		&i.CacheRefresh,
		&i.CacheRefreshInterval,
		&i.CacheLinkPrefetch,
		&i.CacheBypassUrls,
		&i.CacheBypassCookies,
		&i.CacheIncludeQueries,
		&i.CacheIncludeCookies,
		&i.CssJsMinify,
		&i.CssRucss,
		&i.CssRucssIncludeSelectors,
		&i.CssJsSelfHostThirdParty,
		&i.JsDelay,
		&i.JsDelayMethod,
		&i.JsDelayExcludes,
		&i.JsDelayThirdParty,
		&i.JsDelayThirdPartyExcludes,
		&i.FontsDisplaySwap,
		&i.FontsOptimizeGoogle,
		&i.FontsPreload,
		&i.LazyLoad,
		&i.LazyLoadExclusions,
		&i.ProperlySizeImages,
		&i.YoutubePlaceholder,
		&i.SelfHostGravatars,
		&i.CdnEnabled,
		&i.CdnUrl,
		&i.CdnFileTypes,
		&i.CdnProvider,
		&i.CdnCredentialsEncrypted,
		&i.DbAutoClean,
		&i.DbAutoCleanInterval,
		&i.DbPostRevisions,
		&i.DbPostAutoDrafts,
		&i.DbPostTrashed,
		&i.DbCommentsSpam,
		&i.DbCommentsTrashed,
		&i.DbTransientsExpired,
		&i.DbOptimizeTables,
		&i.BloatDisableBlockCss,
		&i.BloatDisableDashicons,
		&i.BloatDisableEmojis,
		&i.BloatDisableJqueryMigrate,
		&i.BloatDisableXmlRpc,
		&i.BloatDisableRssFeed,
		&i.BloatDisableOembeds,
		&i.BloatHeartbeatControl,
		&i.BloatPostRevisionsControl,
		&i.ServerSoftware,
		&i.DropinInstalled,
		&i.WpCacheConstantSet,
		&i.HtaccessManaged,
		&i.ConfigVersion,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertRucssResult = `-- name: UpsertRucssResult :one
INSERT INTO rucss_results (
    tenant_id, site_id, structure_hash, url,
    original_css_bytes, used_css_bytes, reduction_pct, used_css_s3_key,
    selectors_total, selectors_kept, selectors_dropped, compute_ms,
    last_used_at
) VALUES (
    $1, $2, $3, $4,
    $5, $6, $7, $8,
    $9, $10, $11, $12,
    now()
)
ON CONFLICT (site_id, structure_hash) DO UPDATE SET
    url                = EXCLUDED.url,
    original_css_bytes = EXCLUDED.original_css_bytes,
    used_css_bytes     = EXCLUDED.used_css_bytes,
    reduction_pct      = EXCLUDED.reduction_pct,
    used_css_s3_key    = EXCLUDED.used_css_s3_key,
    selectors_total    = EXCLUDED.selectors_total,
    selectors_kept     = EXCLUDED.selectors_kept,
    selectors_dropped  = EXCLUDED.selectors_dropped,
    compute_ms         = EXCLUDED.compute_ms,
    last_used_at       = now()
RETURNING id, tenant_id, site_id, structure_hash, url, original_css_bytes, used_css_bytes, reduction_pct, used_css_s3_key, selectors_total, selectors_kept, selectors_dropped, compute_ms, created_at, last_used_at
`

type UpsertRucssResultParams struct {
	TenantID         uuid.UUID      `json:"tenant_id"`
	SiteID           uuid.UUID      `json:"site_id"`
	StructureHash    string         `json:"structure_hash"`
	Url              *string        `json:"url"`
	OriginalCssBytes *int32         `json:"original_css_bytes"`
	UsedCssBytes     *int32         `json:"used_css_bytes"`
	ReductionPct     pgtype.Numeric `json:"reduction_pct"`
	UsedCssS3Key     string         `json:"used_css_s3_key"`
	SelectorsTotal   *int32         `json:"selectors_total"`
	SelectorsKept    *int32         `json:"selectors_kept"`
	SelectorsDropped *int32         `json:"selectors_dropped"`
	ComputeMs        *int32         `json:"compute_ms"`
}

func (q *Queries) UpsertRucssResult(ctx context.Context, arg UpsertRucssResultParams) (RucssResult, error) {
	row := q.db.QueryRow(ctx, upsertRucssResult,
		arg.TenantID,
		arg.SiteID,
		arg.StructureHash,
		arg.Url,
		arg.OriginalCssBytes,
		arg.UsedCssBytes,
		arg.ReductionPct,
		arg.UsedCssS3Key,
		arg.SelectorsTotal,
		arg.SelectorsKept,
		arg.SelectorsDropped,
		arg.ComputeMs,
	)
	var i RucssResult
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.SiteID,
		&i.StructureHash,
		&i.Url,
		&i.OriginalCssBytes,
		&i.UsedCssBytes,
		&i.ReductionPct,
		&i.UsedCssS3Key,
		&i.SelectorsTotal,
		&i.SelectorsKept,
		&i.SelectorsDropped,
		&i.ComputeMs,
		&i.CreatedAt,
		&i.LastUsedAt,
	)
	return i, err
}
