// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	// Deletes a tenant ONLY if it has no memberships and no sites, returning whether
	// a row was removed. Delegates to the SECURITY DEFINER admin_delete_empty_tenant
	// function: the tenant's ON DELETE CASCADE reaches audit_log, which wpmgr_app may
	// NOT delete (insert-only), so a direct DELETE fails 42501. The function runs as
	// its owner (which keeps DELETE on audit_log) and pins app.agent='on' so its
	// emptiness checks see rows under FORCE RLS.
	AdminDeleteEmptyTenant(ctx context.Context, tenantID uuid.UUID) (bool, error)
	AdminDeleteUser(ctx context.Context, id uuid.UUID) (int64, error)
	// Lightweight superadmin fetch that includes is_superadmin.
	AdminGetUserByID(ctx context.Context, id uuid.UUID) (AdminGetUserByIDRow, error)
	AdminInstanceStats(ctx context.Context) (AdminInstanceStatsRow, error)
	// List all users across the instance with org_count (number of memberships).
	// search filters email or name case-insensitively; pass NULL to list all.
	// Ordered by created_at DESC, id DESC (stable keyset). Used only by the
	// superadmin area; it bypasses the tenant-scoped InTenantTx path.
	AdminListUsers(ctx context.Context, arg AdminListUsersParams) ([]AdminListUsersRow, error)
	// Boot seeder only. Sets is_superadmin=true for an email if the user exists.
	// No-op for unknown emails.
	AdminSetSuperadminByEmail(ctx context.Context, email string) error
	AdminSetUserStatus(ctx context.Context, arg AdminSetUserStatusParams) (AdminSetUserStatusRow, error)
	// Tenants where @user_id is the ONLY member (so deleting them orphans the org),
	// with each tenant's name + site count. Run under Pool.InAgentTx
	// (memberships_agent + sites_agent) so the cross-tenant read is allowed.
	AdminUserSoleTenants(ctx context.Context, userID uuid.UUID) ([]AdminUserSoleTenantsRow, error)
	// Records that a scheduled backup was enqueued and advances next_run_at. The
	// scheduler resolves the tenant from the due-row first, then advances within
	// that tenant's scope (the per-tenant isolation policy permits the UPDATE).
	AdvanceBackupScheduleRun(ctx context.Context, arg AdvanceBackupScheduleRunParams) (BackupSchedule, error)
	AllPluginSignatures(ctx context.Context) ([]PluginSignature, error)
	// any-non-archived → archived (operator terminal soft-delete). Sets archived_at;
	// hidden from the default list (connection_state <> 'archived').
	ArchiveSite(ctx context.Context, arg ArchiveSiteParams) (Site, error)
	// Enroll path (app.enroll GUC): the site-first consume transition. Stores the
	// agent key on the pre-existing pending_enrollment site and moves it to
	// connected in one statement. The generation was already advanced at re-enroll
	// mint time (BeginSiteReEnrollment), so we do not bump it here. Mirrors the
	// legacy AttachAgentToSite but driving connection_state.
	// Defense-in-depth (Phase 6 review, finding E): consume only from
	// 'pending_enrollment'. A code is bound to a site BeginReEnrollment already moved
	// to pending_enrollment, so this holds on the happy path; the guard stops a
	// stale-but-valid code from forcing a connected/degraded/revoked/archived site
	// back to 'connected' out of sequence (a loser yields ErrNoRows like an expired code).
	AttachAgentAndConnect(ctx context.Context, arg AttachAgentAndConnectParams) (Site, error)
	// Re-enrollment: rotate the agent key and mark the site active/enrolled again.
	AttachAgentToSite(ctx context.Context, arg AttachAgentToSiteParams) (Site, error)
	// revoked/disconnected/archived → pending_enrollment (operator). Bumps the
	// generation counter and clears archived_at so the row leaves the archived list.
	// The next consume increments nothing further — generation already advanced.
	BeginSiteReEnrollment(ctx context.Context, arg BeginSiteReEnrollmentParams) (Site, error)
	// Clear the in-flight db_clean watchdog columns on completion or failure.
	ClearActiveDBCleanJob(ctx context.Context, siteID uuid.UUID) error
	// Clear the in-flight db_scan watchdog columns on completion or failure.
	ClearActiveDBScanJob(ctx context.Context, siteID uuid.UUID) error
	CompleteBackupSnapshot(ctx context.Context, arg CompleteBackupSnapshotParams) (BackupSnapshot, error)
	// Consume path (app.agent). Atomic single-shot UPDATE that wins exactly once
	// across concurrent agent callbacks: the (consumed_at IS NULL) predicate makes
	// the second consume a 0-row update; RETURNING tells the caller it lost. The
	// site_id check binds the consume to the agent's verified identity (anti
	// cross-tenant replay).
	ConsumeAutologinToken(ctx context.Context, arg ConsumeAutologinTokenParams) (ConsumeAutologinTokenRow, error)
	// Atomically consume an unused, unexpired verification token.
	ConsumeEmailVerificationToken(ctx context.Context, tokenHash []byte) (EmailVerificationToken, error)
	// Enroll path (app.enroll GUC): mark consumed only if still unconsumed.
	ConsumePairingCode(ctx context.Context, id uuid.UUID) (int64, error)
	// Atomically consume a token: mark it used IFF it exists, is unused, and is not
	// expired. Returns the row (incl. user_id) only when the consume succeeded, so
	// the caller cannot distinguish wrong/expired/used by anything but "no row".
	ConsumePasswordResetToken(ctx context.Context, tokenHash []byte) (PasswordResetToken, error)
	// Enroll path (app.enroll GUC): the ATOMIC single-use consume. Marks the code
	// consumed only if it is still unconsumed AND unexpired, recording the source
	// IP. Exactly one concurrent caller wins (the conditional UPDATE is the lock);
	// a loser gets pgx.ErrNoRows. Returns the resolved tenant_id + site_id so the
	// caller can transition the bound site. NULL site_id ⇒ legacy create-at-enroll.
	ConsumeSiteBoundPairingCode(ctx context.Context, arg ConsumeSiteBoundPairingCodeParams) (ConsumeSiteBoundPairingCodeRow, error)
	// Best-effort per-tenant in-flight task count, used by the parallelism guard so
	// one tenant cannot saturate the worker pool. Runs in the tenant's RLS scope.
	CountRunningTasksForTenant(ctx context.Context, tenantID uuid.UUID) (int64, error)
	// Counts tasks not yet in a terminal state, used to decide when a run completes.
	CountUnfinishedTasksForRun(ctx context.Context, arg CountUnfinishedTasksForRunParams) (int64, error)
	CountUsers(ctx context.Context) (int64, error)
	CreateAPIKey(ctx context.Context, arg CreateAPIKeyParams) (ApiKey, error)
	// M4 backup queries. Every statement is tenant-scoped both explicitly
	// (tenant_id in the WHERE/VALUES) and by RLS (the app.tenant_id policy).
	// ---------------------------------------------------------------------------
	// backup_snapshots
	// ---------------------------------------------------------------------------
	CreateBackupSnapshot(ctx context.Context, arg CreateBackupSnapshotParams) (BackupSnapshot, error)
	CreateInvitation(ctx context.Context, arg CreateInvitationParams) (Invitation, error)
	// ---------------------------------------------------------------------------
	// backup_manifest_entries
	// ---------------------------------------------------------------------------
	CreateManifestEntry(ctx context.Context, arg CreateManifestEntryParams) (BackupManifestEntry, error)
	CreateMembership(ctx context.Context, arg CreateMembershipParams) (Membership, error)
	// Tenant-scoped (app.tenant_id) — operator generates a code for the tenant.
	CreatePairingCode(ctx context.Context, arg CreatePairingCodeParams) (PairingCode, error)
	// Site-first "Add site" flow (ADR-041): create the sites row in
	// pending_enrollment BEFORE the agent enrolls, so the enrollment code can be
	// bound to a real site_id and the dashboard can subscribe to it immediately.
	CreatePendingSite(ctx context.Context, arg CreatePendingSiteParams) (Site, error)
	// Upsert on (site_id, user_id): if a share already exists for this (site, user)
	// pair, update the role, granted_by and expires_at in place.
	CreateShare(ctx context.Context, arg CreateShareParams) (SiteShare, error)
	// tenant_id is supplied explicitly for defense-in-depth; RLS additionally
	// enforces that it matches the current app.tenant_id setting.
	CreateSite(ctx context.Context, arg CreateSiteParams) (Site, error)
	// ---------------------------------------------------------------------------
	// M21 — site-bound pairing codes (live enrollment + re-enroll, ADR-041).
	// ---------------------------------------------------------------------------
	// Tenant-scoped (app.tenant_id): mint a code bound to an existing site_id (the
	// site already exists in pending_enrollment). Consuming this code transitions
	// THAT site to connected rather than creating a new row.
	CreateSiteBoundPairingCode(ctx context.Context, arg CreateSiteBoundPairingCodeParams) (PairingCode, error)
	CreateSiteForEnroll(ctx context.Context, arg CreateSiteForEnrollParams) (Site, error)
	CreateTenant(ctx context.Context, arg CreateTenantParams) (Tenant, error)
	// M3 bulk-update queries. Every statement is tenant-scoped both explicitly
	// (tenant_id in the WHERE/VALUES) and by RLS (the app.tenant_id policy).
	// tenant_id is supplied explicitly for defense-in-depth; RLS additionally
	// enforces it matches the current app.tenant_id setting.
	CreateUpdateRun(ctx context.Context, arg CreateUpdateRunParams) (UpdateRun, error)
	CreateUpdateTask(ctx context.Context, arg CreateUpdateTaskParams) (UpdateTask, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	// Decrements but never below zero. Returns the new refcount + s3_key so the GC
	// job can delete the object from storage when the count reaches zero.
	DecrementChunkRefcount(ctx context.Context, arg DecrementChunkRefcountParams) (DecrementChunkRefcountRow, error)
	DeleteBackupSnapshot(ctx context.Context, arg DeleteBackupSnapshotParams) (int64, error)
	// Hard-delete a site that has never connected. The delete is conditional on
	// all three never-connected predicates (connection_state='pending_enrollment',
	// enrolled_at IS NULL, agent_public_key empty) so the guard and delete are
	// atomic in the same tenant tx. rowsAffected==0 means the site raced to
	// connected and must be treated as not_cancellable by the service layer.
	DeleteCancellableSite(ctx context.Context, arg DeleteCancellableSiteParams) (int64, error)
	DeleteMembership(ctx context.Context, arg DeleteMembershipParams) (int64, error)
	// Deletes a chunk row only if its refcount is zero (the object was already
	// removed from storage by the GC job). Tenant-scoped.
	DeleteOrphanChunk(ctx context.Context, arg DeleteOrphanChunkParams) (int64, error)
	DeleteShare(ctx context.Context, arg DeleteShareParams) (int64, error)
	DeleteSite(ctx context.Context, arg DeleteSiteParams) (int64, error)
	FailBackupSnapshot(ctx context.Context, arg FailBackupSnapshotParams) (BackupSnapshot, error)
	// Records a terminal task state (succeeded|failed|rolled_back|skipped) with the
	// resolved versions and any detail/error. Tenant-scoped by id+tenant_id.
	FinishUpdateTask(ctx context.Context, arg FinishUpdateTaskParams) (UpdateTask, error)
	GetAPIKey(ctx context.Context, arg GetAPIKeyParams) (ApiKey, error)
	// GetAPIKeyByPrefix resolves a presented key by its unique prefix. This runs
	// WITHOUT a tenant GUC (the auth layer does not yet know the tenant), so it must
	// be executed via InAdminTx which sets app.tenant_id to the row's own tenant is
	// impossible chicken/egg — instead this query is run with RLS disabled scope by
	// using the prefix-unique lookup helper that sets the GUC after. See repo.
	GetAPIKeyByPrefix(ctx context.Context, prefix string) (ApiKey, error)
	// Auth-time allowlist resolver: returns all non-expired site shares for a given
	// (user, tenant) pair. The result is used to build the AllowedSiteIDs list for a
	// site-scoped principal. Run under InUserTx (app.user_id set) or directly with
	// explicit params.
	GetActiveSharesForUserTenant(ctx context.Context, arg GetActiveSharesForUserTenantParams) ([]SiteShare, error)
	// M5 uptime alerting: per-tenant alert config + per-site alert state.
	// Tenant-scoped read of the tenant's default alert channel.
	GetAlertConfig(ctx context.Context, tenantID uuid.UUID) (AlertConfig, error)
	// Mint path (app.tenant_id). When no row exists the service auto-creates the
	// default policy on first read (see UpsertAutologinPolicyDefault).
	GetAutologinPolicy(ctx context.Context, arg GetAutologinPolicyParams) (AutologinPolicy, error)
	// Consume path (app.agent). Cross-tenant SELECT-only read of the policy so the
	// agent learns which WP roles it may log in as. NULL row -> defaults applied.
	GetAutologinPolicyForAgent(ctx context.Context, siteID uuid.UUID) (AutologinPolicy, error)
	// ---------------------------------------------------------------------------
	// backup_chunks  (content-addressed dedup + refcount GC)
	// ---------------------------------------------------------------------------
	GetBackupChunk(ctx context.Context, arg GetBackupChunkParams) (BackupChunk, error)
	// ---------------------------------------------------------------------------
	// backup_schedules
	// ---------------------------------------------------------------------------
	GetBackupScheduleForSite(ctx context.Context, arg GetBackupScheduleForSiteParams) (BackupSchedule, error)
	// Returns the site fields the backup scheduler needs: enrollment status,
	// agent URL, age recipient for encryption, and the WP timezone columns
	// added in M17 (wp_timezone IANA name + wp_gmt_offset fallback).
	// Runs tenant-scoped (the caller sets app.tenant_id before this query).
	GetBackupSiteInfo(ctx context.Context, arg GetBackupSiteInfoParams) (GetBackupSiteInfoRow, error)
	GetBackupSnapshot(ctx context.Context, arg GetBackupSnapshotParams) (BackupSnapshot, error)
	// ---------------------------------------------------------------------------
	// site_cache_stats
	// ---------------------------------------------------------------------------
	GetCacheStats(ctx context.Context, siteID uuid.UUID) (SiteCacheStat, error)
	// Returns the latest scan result for a site (tenant-scoped via RLS).
	GetDBScanResult(ctx context.Context, arg GetDBScanResultParams) (SiteDbScanResult, error)
	// Returns up to 366 data points for the trend chart, ordered oldest-first.
	// The caller passes the cutoff as a timestamptz (now() - interval).
	// Tenant-scoped via RLS (InTenantTx sets app.tenant_id).
	GetDBSizeHistory(ctx context.Context, arg GetDBSizeHistoryParams) ([]SiteDbSizeHistory, error)
	// ---------------------------------------------------------------------------
	// db-clean scheduling (M38)
	// ---------------------------------------------------------------------------
	// Returns up to @limit site_perf_config rows where db_auto_clean=true and the
	// site is due for cleanup (next_db_clean_at IS NULL means first-run-ever and
	// is treated as immediately due). Runs under app.agent (cross-tenant sweep).
	GetDueDBCleanSites(ctx context.Context, rowLimit int32) ([]GetDueDBCleanSitesRow, error)
	// ---------------------------------------------------------------------------
	// P3.7 — Fleet / Portfolio DB Health aggregate (tenant-level, no site_id param)
	// ---------------------------------------------------------------------------
	// Returns one row per site that has a scan result, with the site name, latest
	// db_size_bytes, table_count, orphan counts from stored JSONB arrays, and a
	// growth_bytes derived from the earliest vs latest size-history points.
	// Tenant-scoped via RLS (InTenantTx sets app.tenant_id). Top-N ordering is
	// applied by the caller; this returns ALL scanned sites so the service can
	// compute tenant-level aggregates and then slice the top-N list.
	GetFleetDbHealth(ctx context.Context, arg GetFleetDbHealthParams) ([]GetFleetDbHealthRow, error)
	// By-id load for the per-site invitation management routes (revoke/regenerate).
	// Tenant isolation is enforced by RLS; the handler additionally verifies
	// site_id + scope against the path before mutating.
	GetInvitationByID(ctx context.Context, id uuid.UUID) (Invitation, error)
	// Pre-auth lookup: must be run under InInviteLookupTx (app.invite_lookup='on').
	GetInvitationByTokenHash(ctx context.Context, tokenHash string) (Invitation, error)
	GetLastAuditHash(ctx context.Context, tenantID uuid.UUID) (string, error)
	GetMembership(ctx context.Context, arg GetMembershipParams) (Membership, error)
	// Enroll path (app.enroll GUC): resolve a presented code by its hash before the
	// tenant is known.
	GetPairingCodeByHash(ctx context.Context, codeHash string) (PairingCode, error)
	// M36 Performance Suite queries (ADR-046). Every statement is tenant-scoped both
	// explicitly (tenant_id in the WHERE/VALUES) and by RLS (the app.tenant_id
	// policy / app.agent policy). The repo wraps each call in InTenantTx/InAgentTx —
	// these queries never set GUCs themselves. updated_at is set here via now().
	// ---------------------------------------------------------------------------
	// site_perf_config
	// ---------------------------------------------------------------------------
	GetPerfConfig(ctx context.Context, siteID uuid.UUID) (SitePerfConfig, error)
	// M40 plugin_signatures queries.
	// Global reference data (no tenant_id). The corpus table uses ENABLE RLS with a
	// permissive SELECT policy; wpmgr_app has SELECT only. These queries run under the
	// normal pool (no tenant GUC needed — any authenticated session may read).
	GetPluginSignatureBySlug(ctx context.Context, slug string) (PluginSignature, error)
	GetRucssJob(ctx context.Context, arg GetRucssJobParams) (RucssJob, error)
	// ---------------------------------------------------------------------------
	// rucss_results
	// ---------------------------------------------------------------------------
	GetRucssResultByHash(ctx context.Context, arg GetRucssResultByHashParams) (RucssResult, error)
	// Fetch the single instance SMTP row. Run under Pool.InAgentTx (app.agent='on').
	GetSMTPSettings(ctx context.Context) (SmtpSetting, error)
	GetScheduleRun(ctx context.Context, arg GetScheduleRunParams) (BackupScheduleRun, error)
	GetSite(ctx context.Context, arg GetSiteParams) (Site, error)
	// Cross-tenant read of one site's alert state (app.agent GUC) for the probe job.
	GetSiteAlertState(ctx context.Context, siteID uuid.UUID) (SiteAlertState, error)
	// ---------------------------------------------------------------------------
	// Agent-auth path (app.agent GUC). Resolve a site by its agent public key.
	// ---------------------------------------------------------------------------
	GetSiteByAgentKey(ctx context.Context, agentPublicKey string) (Site, error)
	// ---------------------------------------------------------------------------
	// Enrollment path (app.enroll GUC). These run before any tenant scope exists.
	// ---------------------------------------------------------------------------
	GetSiteByURLForEnroll(ctx context.Context, arg GetSiteByURLForEnrollParams) (Site, error)
	// Loads one event under the tenant scope (the LISTEN listener uses this after a
	// NOTIFY to fetch the body it must fan out).
	GetSiteEvent(ctx context.Context, arg GetSiteEventParams) (SiteEvent, error)
	// M21 — Connection lifecycle (Phase 5.7, ADR-038/039/040/041).
	//
	// These queries drive the ConnectionService state machine, the SSE event
	// journal, and the timeout sweeper. The state machine is enforced in Go
	// (site.CanTransition); the SQL here performs the load + the single-state
	// write inside one InTenantTx (or InEnrollTx for the pre-tenant consume path).
	// ---------------------------------------------------------------------------
	// Site load for a read-modify-write transition (tenant-scoped, FOR UPDATE).
	// ---------------------------------------------------------------------------
	// URL-dedup check before MintEnrollmentCode. Tenant-scoped; includes ALL states
	// (archived, pending, etc.) so that a tombstone is visible and the caller can
	// return a structured 409 with site_id + connection_state.
	GetSiteByURLForMint(ctx context.Context, arg GetSiteByURLForMintParams) (GetSiteByURLForMintRow, error)
	// Loads a site under the tenant scope with a row lock so the load → validate →
	// write sequence is serialized against concurrent transitions on the same row.
	GetSiteForTransition(ctx context.Context, arg GetSiteForTransitionParams) (Site, error)
	// ---------------------------------------------------------------------------
	// Timeout-sweeper selects (cross-tenant, app.agent GUC). Both scan the partial
	// idx_sites_last_seen index (connected/degraded only).
	// ---------------------------------------------------------------------------
	// Resolves a site's tenant by id (cross-tenant, app.agent GUC). Used by the
	// tenant-less ConnectionService entry points (MarkDegraded/MarkDisconnected/
	// RecordLastWill) to recover the tenant scope before the tenant-scoped write.
	GetSiteTenant(ctx context.Context, id uuid.UUID) (uuid.UUID, error)
	// Returns site_perf_config rows with a stalled db_clean job (started but no
	// terminal event within the threshold). Runs under app.agent (cross-tenant).
	GetStalledDBCleanJobs(ctx context.Context, cleanThreshold pgtype.Interval) ([]GetStalledDBCleanJobsRow, error)
	// Returns site_perf_config rows with a stalled db_scan job (started but no
	// result within the threshold). Runs under app.agent (cross-tenant).
	GetStalledDBScanJobs(ctx context.Context, scanThreshold pgtype.Interval) ([]GetStalledDBScanJobsRow, error)
	GetTenant(ctx context.Context, id uuid.UUID) (Tenant, error)
	// GetTenantForUser returns a tenant by id only when the given user is a member.
	// Like ListTenantsForUser it relies on the memberships_self_read policy and must
	// be run via InUserTx; a non-member (or unknown tenant) yields no rows.
	GetTenantForUser(ctx context.Context, arg GetTenantForUserParams) (Tenant, error)
	GetUpdateRun(ctx context.Context, arg GetUpdateRunParams) (UpdateRun, error)
	GetUpdateTask(ctx context.Context, arg GetUpdateTaskParams) (UpdateTask, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByID(ctx context.Context, id uuid.UUID) (User, error)
	GetUserByOIDC(ctx context.Context, arg GetUserByOIDCParams) (User, error)
	// Lightweight per-request lookup for the session reject-stale check.
	GetUserPasswordChangedAt(ctx context.Context, id uuid.UUID) (pgtype.Timestamptz, error)
	IncrEmailAttempts(ctx context.Context, id uuid.UUID) error
	IncrementChunkRefcount(ctx context.Context, arg IncrementChunkRefcountParams) (BackupChunk, error)
	IncrementInviteAttempts(ctx context.Context, id uuid.UUID) (Invitation, error)
	// Enroll path (app.enroll GUC): record a failed validation attempt.
	IncrementPairingCodeAttempts(ctx context.Context, id uuid.UUID) (int64, error)
	// Agent-auth path (app.agent GUC). The unique (site_id, nonce) index makes a
	// replayed nonce a no-op via ON CONFLICT, returning 0 rows affected.
	InsertAgentNonce(ctx context.Context, arg InsertAgentNonceParams) (int64, error)
	InsertAuditEntry(ctx context.Context, arg InsertAuditEntryParams) (AuditLog, error)
	// ============================================================================
	// autologin (Phase 5.5 — One-Click Login) sqlc queries.
	//
	// The MINT path runs tenant-scoped (app.tenant_id) so RLS isolates the
	// INSERT. The CONSUME path runs cross-tenant under app.agent (the agent
	// presents the verified site_id + nonce — no tenant context yet); the
	// autologin_tokens_agent / autologin_tokens_agent_consume policies cover it.
	// The same policy split applies to autologin_policies (tenant-scoped read/
	// upsert + cross-tenant SELECT under app.agent for the agent's roles lookup).
	// ============================================================================
	// Mint path (app.tenant_id). The id is the JWT jti (base64url 32B random).
	InsertAutologinToken(ctx context.Context, arg InsertAutologinTokenParams) (AutologinToken, error)
	// ---------------------------------------------------------------------------
	// cache_purge_audit
	// ---------------------------------------------------------------------------
	InsertCachePurgeAudit(ctx context.Context, arg InsertCachePurgeAuditParams) (CachePurgeAudit, error)
	// ---------------------------------------------------------------------------
	// site_connection_history — append-only transition log (tenant-scoped).
	// ---------------------------------------------------------------------------
	InsertConnectionHistory(ctx context.Context, arg InsertConnectionHistoryParams) (SiteConnectionHistory, error)
	// ---------------------------------------------------------------------------
	// site_db_size_history (M42)
	// ---------------------------------------------------------------------------
	// Appends one size data point after a successful db_scan.
	// Called from the same InTenantTx as UpsertDBScanResult so both land
	// atomically. ON CONFLICT DO NOTHING on (site_id, scanned_at) prevents
	// duplicate rows if the operator retriggers a scan within the same second.
	InsertDBSizeHistory(ctx context.Context, arg InsertDBSizeHistoryParams) (SiteDbSizeHistory, error)
	// Record a queued email before enqueuing the send_email job. Run under
	// Pool.InAgentTx (app.agent='on'); tenant_id may be NULL for auth mail.
	InsertEmailLog(ctx context.Context, arg InsertEmailLogParams) (EmailLog, error)
	// Run under Pool.InAgentTx (app.agent='on').
	InsertEmailVerificationToken(ctx context.Context, arg InsertEmailVerificationTokenParams) (EmailVerificationToken, error)
	// Record a new reset token. Run under Pool.InAgentTx (app.agent='on').
	InsertPasswordResetToken(ctx context.Context, arg InsertPasswordResetTokenParams) (PasswordResetToken, error)
	// ---------------------------------------------------------------------------
	// rucss_jobs
	// ---------------------------------------------------------------------------
	InsertRucssJob(ctx context.Context, arg InsertRucssJobParams) (RucssJob, error)
	// ---------------------------------------------------------------------------
	// site_events — durable SSE journal (tenant-scoped insert/replay, cross-tenant
	// prune). The app mints the ULID event_id; NOTIFY carries only the id.
	// ---------------------------------------------------------------------------
	InsertSiteEvent(ctx context.Context, arg InsertSiteEventParams) (SiteEvent, error)
	InvalidateUserEmailVerificationTokens(ctx context.Context, userID uuid.UUID) error
	// Burn all outstanding reset tokens for a user (after a successful reset/change).
	InvalidateUserPasswordResetTokens(ctx context.Context, userID uuid.UUID) error
	LinkUserOIDC(ctx context.Context, arg LinkUserOIDCParams) (User, error)
	ListAPIKeys(ctx context.Context, arg ListAPIKeysParams) ([]ApiKey, error)
	// Cross-tenant enumeration for the evaluator (app.agent GUC). Only enabled
	// configs are returned.
	ListAlertConfigsAllTenants(ctx context.Context) ([]AlertConfig, error)
	ListAuditEntries(ctx context.Context, arg ListAuditEntriesParams) ([]AuditLog, error)
	ListAuditEntriesForVerify(ctx context.Context, tenantID uuid.UUID) ([]AuditLog, error)
	// Returns the tenant's already-stored chunks among the given hashes (dedup: the
	// agent only uploads hashes NOT returned here).
	ListBackupChunksByHashes(ctx context.Context, arg ListBackupChunksByHashesParams) ([]BackupChunk, error)
	// Distinct site IDs that have at least one snapshot in this tenant (GC iterates
	// per site to apply the per-site monthly-archive rule).
	ListBackupSiteIDsForTenant(ctx context.Context, tenantID uuid.UUID) ([]uuid.UUID, error)
	ListBackupSnapshotsForSite(ctx context.Context, arg ListBackupSnapshotsForSiteParams) ([]BackupSnapshot, error)
	ListCachePurgeAuditForSite(ctx context.Context, arg ListCachePurgeAuditForSiteParams) ([]CachePurgeAudit, error)
	// Completed snapshots for a site, newest first, used to compute the retention
	// archive set (newest per calendar month).
	ListCompletedSnapshotsForSite(ctx context.Context, arg ListCompletedSnapshotsForSiteParams) ([]ListCompletedSnapshotsForSiteRow, error)
	// Newest first; used by the per-site lifecycle timeline.
	ListConnectionHistory(ctx context.Context, arg ListConnectionHistoryParams) ([]SiteConnectionHistory, error)
	// Cross-tenant enumeration of enabled schedules whose next_run_at has passed,
	// for the periodic scheduler. Runs under the app.agent GUC (scheduler policy).
	ListDueBackupSchedules(ctx context.Context, arg ListDueBackupSchedulesParams) ([]BackupSchedule, error)
	// ---------------------------------------------------------------------------
	// Health-check job (runs in each enrolled site's tenant scope).
	// ---------------------------------------------------------------------------
	// Cross-tenant enumeration for the periodic health job. Runs under the
	// app.agent GUC (sites_agent policy) since it spans tenants.
	ListEnrolledSitesAllTenants(ctx context.Context) ([]ListEnrolledSitesAllTenantsRow, error)
	// Cross-tenant enumeration of enrolled sites WITH their URL for the M5 uptime
	// probe job. Runs under the app.agent GUC (sites_agent policy) since it spans
	// tenants. Only enrolled sites have an agent URL worth probing.
	ListEnrolledSitesForProbe(ctx context.Context) ([]ListEnrolledSitesForProbeRow, error)
	// Completed snapshots older than the cutoff that are NOT archive-retained, in a
	// single tenant scope. The GC job decrements chunk refcounts for each then
	// deletes the snapshot (manifest entries cascade).
	ListExpiredBackupSnapshots(ctx context.Context, arg ListExpiredBackupSnapshotsParams) ([]BackupSnapshot, error)
	// Link history for one site: pending + accepted + expired + revoked, newest
	// first. Tenant-scoped by RLS; site-bound + scope-bound here. The caller derives
	// the display status (pending/accepted/expired/revoked) from the columns.
	ListInvitationsForSite(ctx context.Context, arg ListInvitationsForSiteParams) ([]Invitation, error)
	// The most-recent backup snapshot per site, for the sites-table "Backup" column.
	// DISTINCT ON + ORDER BY (site_id, created_at DESC) is served by
	// backup_snapshots_tenant_site_idx (tenant_id, site_id, created_at DESC) — one
	// index-only seek per site, fetched in a single batched call for the listed ids.
	ListLatestBackupsForSites(ctx context.Context, arg ListLatestBackupsForSitesParams) ([]ListLatestBackupsForSitesRow, error)
	ListManifestEntries(ctx context.Context, arg ListManifestEntriesParams) ([]BackupManifestEntry, error)
	ListMembershipsForTenant(ctx context.Context, arg ListMembershipsForTenantParams) ([]Membership, error)
	// ListMembershipsForUser reads the caller's own memberships across all tenants.
	// It relies on the memberships_self_read policy (app.user_id GUC), so it must be
	// run via InUserTx, not InTenantTx.
	ListMembershipsForUser(ctx context.Context, userID uuid.UUID) ([]Membership, error)
	// ListOrgsForUser returns the user's organisations with their role in each, for
	// the org switcher + settings (real names, not bare ids). Joins memberships under
	// the memberships_self_read policy (app.user_id GUC) so it MUST run via InUserTx.
	ListOrgsForUser(ctx context.Context, userID uuid.UUID) ([]ListOrgsForUserRow, error)
	// Terminal runs (completed/failed/skipped/canceled) for a site, newest first.
	ListPastScheduleRuns(ctx context.Context, arg ListPastScheduleRunsParams) ([]BackupScheduleRun, error)
	// List pending (not yet accepted, not expired, not revoked) invitations for the
	// current tenant.
	ListPendingInvitations(ctx context.Context, tenantID uuid.UUID) ([]Invitation, error)
	ListRucssResultsForSite(ctx context.Context, arg ListRucssResultsForSiteParams) ([]RucssResult, error)
	// All runs for a site (upcoming + past), newest scheduled_for first.
	ListScheduleRunsBySite(ctx context.Context, arg ListScheduleRunsBySiteParams) ([]BackupScheduleRun, error)
	// Shared-with-me, ENRICHED with each site's url + name and the owning org's name.
	// Runs under InUserTx: site_shares_self_read exposes the share rows, the M22
	// sites_shared_read policy exposes the (cross-tenant) site rows, and tenants has
	// no RLS. So the operator sees url/name/org_name for sites shared with them
	// without any membership in the owning org.
	ListSharedSitesForUser(ctx context.Context, userID uuid.UUID) ([]ListSharedSitesForUserRow, error)
	ListSharesForSite(ctx context.Context, siteID uuid.UUID) ([]SiteShare, error)
	// Self-read: returns the caller's own non-expired shares across all tenants.
	// Must be run under a tx that sets app.user_id (site_shares_self_read policy).
	ListSharesForUser(ctx context.Context, userID uuid.UUID) ([]SiteShare, error)
	// Defaults to hiding archived sites (ADR-041). When sqlc.narg('state') is set
	// the list is filtered to exactly that connection_state (e.g. 'archived' for
	// the archived chip); when it is NULL every non-archived site is returned.
	ListSites(ctx context.Context, arg ListSitesParams) ([]Site, error)
	// connected sites whose last heartbeat is older than the degrade cutoff.
	ListSitesToDegrade(ctx context.Context, lastSeenAt pgtype.Timestamptz) ([]ListSitesToDegradeRow, error)
	// degraded sites whose last heartbeat is older than the disconnect cutoff.
	ListSitesToDisconnect(ctx context.Context, lastSeenAt pgtype.Timestamptz) ([]ListSitesToDisconnectRow, error)
	// Watchdog feeder: a running snapshot whose latest progress is older than the
	// stall threshold (or whose runner never reported any progress despite being
	// running for longer than the threshold). The new index
	// backup_snapshots_running_progress_idx makes the predicate selective.
	// Cross-tenant select via the GC RLS policy (app.agent='on').
	ListStalledRunningSnapshots(ctx context.Context, dollar_1 pgtype.Interval) ([]ListStalledRunningSnapshotsRow, error)
	ListTenants(ctx context.Context, arg ListTenantsParams) ([]Tenant, error)
	// ListTenantsForUser returns only the tenants the given user is a member of.
	// It joins memberships under the memberships_self_read policy (app.user_id GUC),
	// so it MUST be run via InUserTx; the join itself restricts the result to the
	// caller's own memberships, preventing cross-tenant enumeration.
	ListTenantsForUser(ctx context.Context, arg ListTenantsForUserParams) ([]Tenant, error)
	// Distinct tenant IDs that have at least one completed snapshot, for the
	// periodic retention GC. Runs cross-tenant under the app.agent GUC (the
	// backup_snapshots_gc SELECT policy); the prune then runs per tenant.
	ListTenantsWithCompletedSnapshots(ctx context.Context) ([]uuid.UUID, error)
	// Runs that have not yet fired: status 'scheduled' or 'queued', scheduled_for
	// in the future. Used for the UI upcoming preview (typically 1–3 rows).
	ListUpcomingScheduleRuns(ctx context.Context, arg ListUpcomingScheduleRunsParams) ([]BackupScheduleRun, error)
	ListUpdateRuns(ctx context.Context, arg ListUpdateRunsParams) ([]UpdateRun, error)
	ListUpdateTasksForRun(ctx context.Context, arg ListUpdateTasksForRunParams) ([]UpdateTask, error)
	// Used on the Redis-hot-path success: Redis already produced the payload, but
	// we still UPDATE the PG row so the audit/observability story is complete.
	// Idempotent: returns 0 if another path already marked it (safe).
	MarkAutologinTokenConsumed(ctx context.Context, arg MarkAutologinTokenConsumedParams) (int64, error)
	MarkBackupSnapshotRunning(ctx context.Context, arg MarkBackupSnapshotRunningParams) (BackupSnapshot, error)
	// Stamp the last-purge gauge from the CONTROL PLANE when an operator purge runs
	// (dashboard "Purge everything" / "Purge URL"). The agent's periodic stats push
	// never reports a purge time, so without this the gauge sits at "Never" forever.
	// Sets ONLY the purge columns: on a first-ever insert the other gauges take their
	// schema defaults (0) and the agent fills them in on its next push; on conflict
	// they keep the agent's last-reported values. Paired with UpsertCacheStats's
	// GREATEST so a later agent push cannot wipe or regress this.
	MarkCachePurged(ctx context.Context, arg MarkCachePurgedParams) error
	MarkEmailFailed(ctx context.Context, arg MarkEmailFailedParams) error
	MarkEmailSent(ctx context.Context, id uuid.UUID) error
	MarkInvitationAccepted(ctx context.Context, arg MarkInvitationAcceptedParams) (Invitation, error)
	// ---------------------------------------------------------------------------
	// Connection-state transitions. Each writes connection_state plus the derived
	// legacy status/health_status (ADR-041 keeps the legacy columns in sync), and
	// the relevant timestamp/reason/generation fields.
	// ---------------------------------------------------------------------------
	// pending_enrollment/degraded/disconnected → connected. Refreshes liveness and
	// clears the disconnected_at/reason set by a prior down transition. The legacy
	// status='active'/health_status='healthy' mirror the new connection_state.
	MarkSiteConnected(ctx context.Context, arg MarkSiteConnectedParams) (Site, error)
	// connected → degraded (timeout sweeper only). Legacy health_status mirrors it.
	MarkSiteDegraded(ctx context.Context, arg MarkSiteDegradedParams) (Site, error)
	// degraded → disconnected (timeout sweeper) OR connected/degraded → disconnected
	// (signed agent last-will). Records disconnected_at + the reason.
	MarkSiteDisconnected(ctx context.Context, arg MarkSiteDisconnectedParams) (Site, error)
	// connected/degraded/disconnected → revoked (operator). The agent key is KEPT
	// (NOT nulled) so the agent can still authenticate its next heartbeat and
	// RECEIVE the signed revoke token to tear itself down (Phase 6 finding C). A
	// later re-enroll overwrites agent_public_key on the same row (no unique-index
	// collision), so keeping it is safe. The agent learns of the revoke on its next
	// heartbeat (derived instruction from connection_state='revoked').
	MarkSiteRevoked(ctx context.Context, arg MarkSiteRevokedParams) (Site, error)
	// Marks a site unreachable. Runs under app.agent GUC (cross-tenant job).
	MarkSiteUnreachable(ctx context.Context, id uuid.UUID) (int64, error)
	MarkUpdateTaskRunning(ctx context.Context, arg MarkUpdateTaskRunningParams) (UpdateTask, error)
	// Activate + mark verified (used on self-serve activation and trusted bootstrap).
	MarkUserEmailVerified(ctx context.Context, id uuid.UUID) error
	// Enroll path (app.enroll GUC): resolve whether a presented code is site-bound
	// (returns its site_id) WITHOUT consuming it, so /enroll can route between the
	// site-first consume and the legacy create-at-enroll flow. Does not leak: only
	// the site_id (nullable) is returned, and the caller already holds the code.
	PeekPairingCodeSiteID(ctx context.Context, codeHash string) (pgtype.UUID, error)
	// Drops nonces older than the freshness window; called opportunistically.
	PruneAgentNonces(ctx context.Context, createdAt time.Time) (int64, error)
	// Deletes rows older than the cutoff across ALL tenants (InAgentTx / app.agent).
	// LIMIT 2000 keeps each GC transaction short; the periodic job runs daily so
	// at typical scan frequency the cap is never hit in practice.
	PruneDBSizeHistory(ctx context.Context, cutoff time.Time) (int64, error)
	// Ring-buffer prune: drop events older than the replay window (cross-tenant,
	// app.agent GUC). Bounds table growth.
	PruneSiteEvents(ctx context.Context, createdAt time.Time) (int64, error)
	// Rotate the token of a still-pending invitation: overwrite token_hash (kills
	// the old link), reset expiry + attempts, and clear any prior soft-revoke.
	// Only an un-accepted row is touched (RETURNING -> ErrNoRows if already
	// accepted). The new raw token is generated by the caller.
	RegenerateInvitationToken(ctx context.Context, arg RegenerateInvitationTokenParams) (Invitation, error)
	// Replays events after a client cursor (?since / Last-Event-ID). ULIDs sort
	// lexicographically, so event_id > $2 is monotonic-after.
	ReplaySiteEvents(ctx context.Context, arg ReplaySiteEventsParams) ([]SiteEvent, error)
	// archived → disconnected (operator un-archive). Clears archived_at.
	RestoreSite(ctx context.Context, arg RestoreSiteParams) (Site, error)
	RevokeAPIKey(ctx context.Context, arg RevokeAPIKeyParams) (int64, error)
	// Soft-revoke a still-pending invitation. Idempotent / race-safe: only an
	// un-accepted, un-revoked row is touched (RETURNING -> ErrNoRows if it was
	// accepted or already revoked between load and update).
	RevokeInvitation(ctx context.Context, arg RevokeInvitationParams) (Invitation, error)
	// Stamp the in-flight db_clean job id + start time for the watchdog.
	// Runs under app.agent (cross-tenant scheduled path) or InTenantTx (operator).
	SetActiveDBCleanJob(ctx context.Context, arg SetActiveDBCleanJobParams) error
	// Stamp the in-flight db_scan job id + start time for the watchdog.
	SetActiveDBScanJob(ctx context.Context, arg SetActiveDBScanJobParams) error
	SetBackupSnapshotArchived(ctx context.Context, arg SetBackupSnapshotArchivedParams) error
	// Links the pending snapshot_id to a run and advances its status to 'queued'.
	SetScheduleRunSnapshot(ctx context.Context, arg SetScheduleRunSnapshotParams) (BackupScheduleRun, error)
	// Advances a run to a terminal or intermediate status by its primary key.
	// started_at and finished_at are set conditionally so they are only written
	// once (the scheduler calls this for running→completed/failed transitions).
	SetScheduleRunStatusByID(ctx context.Context, arg SetScheduleRunStatusByIDParams) (BackupScheduleRun, error)
	// Reconciliation path: when the linked snapshot reaches a terminal status,
	// update the run row to match. Keyed on snapshot_id so the snapshot finalize
	// path does not need to carry the run id. Runs tenant-scoped.
	SetScheduleRunStatusBySnapshot(ctx context.Context, arg SetScheduleRunStatusBySnapshotParams) (BackupScheduleRun, error)
	// Stores the per-site age PUBLIC recipient backups are encrypted to. The CP
	// never holds the matching identity (private key); it cannot decrypt backups.
	SetSiteAgeRecipient(ctx context.Context, arg SetSiteAgeRecipientParams) (Site, error)
	// Sets a site's health_status from an M5 probe result (cross-tenant probe job,
	// app.agent GUC). Only writes when the value actually changes to avoid churn.
	SetSiteHealthStatus(ctx context.Context, arg SetSiteHealthStatusParams) (int64, error)
	SetSiteTags(ctx context.Context, arg SetSiteTagsParams) (Site, error)
	SetUpdateRunStatus(ctx context.Context, arg SetUpdateRunStatusParams) (UpdateRun, error)
	// Stamps password_changed_at so the Authenticator invalidates the user's other
	// sessions (ADR-045 Phase 2).
	SetUserPasswordHash(ctx context.Context, arg SetUserPasswordHashParams) error
	SetUserPending(ctx context.Context, id uuid.UUID) error
	TouchAPIKey(ctx context.Context, arg TouchAPIKeyParams) error
	TouchRucssResultLastUsed(ctx context.Context, arg TouchRucssResultLastUsedParams) error
	// ---------------------------------------------------------------------------
	// Heartbeat liveness (tenant-scoped). Returns the current connection_state so
	// the service can decide whether a recovery transition is needed and whether
	// to hand the agent a pending instruction.
	// ---------------------------------------------------------------------------
	// Bumps last_seen_at and returns the post-update row. Does NOT change
	// connection_state (a recovery from degraded/disconnected is a separate,
	// audited transition the service performs explicitly).
	TouchSiteHeartbeat(ctx context.Context, arg TouchSiteHeartbeatParams) (Site, error)
	TouchSiteSeen(ctx context.Context, arg TouchSiteSeenParams) (Site, error)
	TouchUserLogin(ctx context.Context, id uuid.UUID) error
	// M5.6 / ADR-032: agent runner posts a JSONB progress payload at every phpbu
	// stage transition + per-chunk during the custom PresignedS3 Sync. We always
	// replace (no append/history) — the latest phase is what the UI renders, and
	// the watchdog scans by progress_updated_at. Tenant-scoped via RLS; the agent
	// handler injects the tenant from the verified Ed25519 identity, never from
	// the body.
	UpdateBackupSnapshotProgress(ctx context.Context, arg UpdateBackupSnapshotProgressParams) (BackupSnapshot, error)
	UpdateMembershipRole(ctx context.Context, arg UpdateMembershipRoleParams) (Membership, error)
	// Advance the next_db_clean_at timestamp after a clean job is dispatched.
	// Runs under app.agent (the scheduled-dispatch path is cross-tenant).
	UpdateNextDBCleanAt(ctx context.Context, arg UpdateNextDBCleanAtParams) error
	// The agent reports the server/install state it observed when applying config.
	// Kept separate from UpsertPerfConfig so an operator's config save never
	// overwrites agent-reported facts (and vice-versa). Runs under app.agent.
	UpdatePerfInstallState(ctx context.Context, arg UpdatePerfInstallStateParams) (SitePerfConfig, error)
	// Advance the job lifecycle (queued->running->done|failed). completed_at is set
	// (to now()) only when @done is true; result_id/error_reason are passed through
	// as the terminal state dictates.
	UpdateRucssJobState(ctx context.Context, arg UpdateRucssJobStateParams) (RucssJob, error)
	// Tenant-scoped metadata update (used by the agent path inside the resolved
	// site's own tenant scope).
	UpdateSiteMetadata(ctx context.Context, arg UpdateSiteMetadataParams) (Site, error)
	// UpdateTenantName renames a tenant. tenants has no RLS, so the handler verifies
	// the caller's membership + admin/owner role before calling this.
	UpdateTenantName(ctx context.Context, arg UpdateTenantNameParams) (Tenant, error)
	// Tenant-scoped create-or-update of the tenant's default alert channel.
	UpsertAlertConfig(ctx context.Context, arg UpsertAlertConfigParams) (AlertConfig, error)
	// Mint path (app.tenant_id). Idempotent insert-or-return: the first call seeds
	// the default policy (enabled, allowed=administrator, 2FA off, max age 30m);
	// subsequent calls return the existing row unchanged.
	UpsertAutologinPolicyDefault(ctx context.Context, arg UpsertAutologinPolicyDefaultParams) (AutologinPolicy, error)
	// Records a chunk's storage location idempotently. On conflict (the chunk
	// already exists) it leaves size/s3_key as-is (content-addressed: identical
	// hash ⇒ identical bytes) and returns the existing row. refcount is managed
	// separately by IncrementChunkRefcount.
	UpsertBackupChunk(ctx context.Context, arg UpsertBackupChunkParams) (BackupChunk, error)
	// Inserts or updates a backup schedule. next_run_at is intentionally NOT
	// included in the ON CONFLICT DO UPDATE set: the service decides when to
	// recompute it (only when timing fields actually change). This prevents a
	// non-timing edit (e.g. retention_days change) from resetting the next run.
	UpsertBackupSchedule(ctx context.Context, arg UpsertBackupScheduleParams) (BackupSchedule, error)
	// The agent pushes the latest cache gauges; overwritten in place (no history).
	UpsertCacheStats(ctx context.Context, arg UpsertCacheStatsParams) (SiteCacheStat, error)
	// ---------------------------------------------------------------------------
	// site_db_scan_results (M39)
	// ---------------------------------------------------------------------------
	// Persists (or refreshes) the latest db_scan result for a site.
	// Uses upsert so there is always at most one row per site.
	// Phase 2.1: tables_json carries the per-table inventory alongside categories_json.
	// Phase 3.3 (M41): orphaned_options_json, orphaned_cron_json, installed_plugins_json
	//   carry the orphan-enumeration output from agents >= 0.16.0. Agents < 0.16.0
	//   omit these fields; the caller passes '[]' for backward compat.
	UpsertDBScanResult(ctx context.Context, arg UpsertDBScanResultParams) (SiteDbScanResult, error)
	// Tenant-create helper: insert an owner membership for the creator; on conflict
	// (e.g. migration replay or second create attempt) update role to 'owner'.
	UpsertOwnerMembership(ctx context.Context, arg UpsertOwnerMembershipParams) (Membership, error)
	// Insert-or-update the per-site performance config. The agent install-state
	// columns (server_software, dropin_installed, wp_cache_constant_set,
	// htaccess_managed) are NOT touched here — those are reported by the agent via
	// UpdatePerfInstallState — so an operator config save never clobbers them.
	UpsertPerfConfig(ctx context.Context, arg UpsertPerfConfigParams) (SitePerfConfig, error)
	UpsertRucssResult(ctx context.Context, arg UpsertRucssResultParams) (RucssResult, error)
	// Insert-or-update the singleton row. password_enc uses a nil-sentinel:
	// when @set_password is false the existing ciphertext is preserved, so editing
	// other fields without re-entering the password keeps the stored secret.
	UpsertSMTPSettings(ctx context.Context, arg UpsertSMTPSettingsParams) (SmtpSetting, error)
	// M17 backup_schedule_runs queries. Mirrors the restore_runs query style.
	// Every tenant-scoped method is called with app.tenant_id already set.
	// The scheduler's cross-tenant materializer writes run under the agent context
	// (app.agent='on'), like ListDueBackupSchedules.
	// ---------------------------------------------------------------------------
	// backup_schedule_runs
	// ---------------------------------------------------------------------------
	// Pre-inserts the next scheduled run row idempotently. On conflict
	// (schedule_id, scheduled_for) — e.g. CP restart — updates status only when
	// the existing row is still 'scheduled' so a queued/running row is untouched.
	UpsertScheduleRun(ctx context.Context, arg UpsertScheduleRunParams) (BackupScheduleRun, error)
	// Cross-tenant upsert of a site's alert state (app.agent GUC). The probe worker
	// writes the new transition memory after each probe.
	UpsertSiteAlertState(ctx context.Context, arg UpsertSiteAlertStateParams) (SiteAlertState, error)
}

var _ Querier = (*Queries)(nil)
