// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: site_email.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const deleteEmailLogsBulk = `-- name: DeleteEmailLogsBulk :execrows
DELETE FROM site_email_log
WHERE tenant_id = $1
  AND site_id   = $2
  AND id = ANY($3::uuid[])
`

type DeleteEmailLogsBulkParams struct {
	TenantID uuid.UUID   `json:"tenant_id"`
	SiteID   uuid.UUID   `json:"site_id"`
	Ids      []uuid.UUID `json:"ids"`
}

// Bulk delete of log entries by id list. Must be tenant+site scoped (InTenantTx).
// The ids array is the caller-supplied list; RLS provides the second line of defence.
func (q *Queries) DeleteEmailLogsBulk(ctx context.Context, arg DeleteEmailLogsBulkParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteEmailLogsBulk, arg.TenantID, arg.SiteID, arg.Ids)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteEmailLogsOlderThan = `-- name: DeleteEmailLogsOlderThan :execrows
DELETE FROM site_email_log
WHERE id IN (
    SELECT l.id
    FROM site_email_log l
    JOIN site_email_config c
      ON c.tenant_id = l.tenant_id
     AND c.site_id   = l.site_id
    WHERE l.created_at < $1::timestamptz
       OR (
            -- Per-site retention: delete when older than the config's retention_days.
            -- Falls back to 14 days when no per-site config exists (subquery returns NULL).
            l.created_at < now() - (COALESCE(
                (SELECT retention_days FROM site_email_config
                 WHERE tenant_id = l.tenant_id AND site_id = l.site_id
                 LIMIT 1), 14
            ) * INTERVAL '1 day')
          )
    LIMIT $2::bigint
)
`

type DeleteEmailLogsOlderThanParams struct {
	CutoffTs  time.Time `json:"cutoff_ts"`
	BatchSize int64     `json:"batch_size"`
}

// Retention pruner: deletes rows older than the supplied cutoff timestamp.
// Batched via LIMIT so a single invocation does not lock the table for too long.
// The worker calls this in a loop until 0 rows are deleted.
// Cross-tenant (InAgentTx): the agent policy allows full-table access.
func (q *Queries) DeleteEmailLogsOlderThan(ctx context.Context, arg DeleteEmailLogsOlderThanParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteEmailLogsOlderThan, arg.CutoffTs, arg.BatchSize)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteEmailSuppression = `-- name: DeleteEmailSuppression :exec
DELETE FROM email_suppression
WHERE id        = $1
  AND tenant_id = $2
`

type DeleteEmailSuppressionParams struct {
	ID       uuid.UUID `json:"id"`
	TenantID uuid.UUID `json:"tenant_id"`
}

// Operator delete (un-suppress). Must be tenant-scoped (InTenantTx).
func (q *Queries) DeleteEmailSuppression(ctx context.Context, arg DeleteEmailSuppressionParams) error {
	_, err := q.db.Exec(ctx, deleteEmailSuppression, arg.ID, arg.TenantID)
	return err
}

const getEmailConfigByRouteTokenHash = `-- name: GetEmailConfigByRouteTokenHash :one
SELECT id, tenant_id, site_id, provider, from_address, from_name, force_from_email, force_from_name, return_path, config, provider_secret_encrypted, oauth_refresh_encrypted, oauth_access_encrypted, oauth_expires_at, mappings, default_connection, fallback_connection, log_emails, store_body, retention_days, webhook_route_token_hash, webhook_signing_key_enc, ses_topic_arns, created_at, updated_at
FROM site_email_config
WHERE webhook_route_token_hash = $1::bytea
`

// m61: resolve a config row by its webhook_route_token_hash for the public
// webhook dispatcher.  Runs under InAgentTx (webhook path, no tenant GUC).
// Returns the full row so the handler can load and decrypt the per-row signing
// key and verify the provider signature with the right key.
func (q *Queries) GetEmailConfigByRouteTokenHash(ctx context.Context, tokenHash []byte) (SiteEmailConfig, error) {
	row := q.db.QueryRow(ctx, getEmailConfigByRouteTokenHash, tokenHash)
	var i SiteEmailConfig
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.SiteID,
		&i.Provider,
		&i.FromAddress,
		&i.FromName,
		&i.ForceFromEmail,
		&i.ForceFromName,
		&i.ReturnPath,
		&i.Config,
		&i.ProviderSecretEncrypted,
		&i.OauthRefreshEncrypted,
		&i.OauthAccessEncrypted,
		&i.OauthExpiresAt,
		&i.Mappings,
		&i.DefaultConnection,
		&i.FallbackConnection,
		&i.LogEmails,
		&i.StoreBody,
		&i.RetentionDays,
		&i.WebhookRouteTokenHash,
		&i.WebhookSigningKeyEnc,
		&i.SesTopicArns,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getEmailLog = `-- name: GetEmailLog :one
SELECT id, tenant_id, site_id, agent_seq, message_id, to_addresses, from_address, subject, provider, status, response, error, retries, resent_count, body_stored, body, created_at, updated_at
FROM site_email_log
WHERE tenant_id = $1
  AND site_id   = $2
  AND id        = $3
`

type GetEmailLogParams struct {
	TenantID uuid.UUID `json:"tenant_id"`
	SiteID   uuid.UUID `json:"site_id"`
	ID       uuid.UUID `json:"id"`
}

// Fetch a single email log entry by id (operator detail view, includes body).
func (q *Queries) GetEmailLog(ctx context.Context, arg GetEmailLogParams) (SiteEmailLog, error) {
	row := q.db.QueryRow(ctx, getEmailLog, arg.TenantID, arg.SiteID, arg.ID)
	var i SiteEmailLog
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.SiteID,
		&i.AgentSeq,
		&i.MessageID,
		&i.ToAddresses,
		&i.FromAddress,
		&i.Subject,
		&i.Provider,
		&i.Status,
		&i.Response,
		&i.Error,
		&i.Retries,
		&i.ResentCount,
		&i.BodyStored,
		&i.Body,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getEmailLogBodyStored = `-- name: GetEmailLogBodyStored :one
SELECT id, body_stored
FROM site_email_log
WHERE id        = $1
  AND tenant_id = $2
  AND site_id   = $3
`

type GetEmailLogBodyStoredParams struct {
	ID       uuid.UUID `json:"id"`
	TenantID uuid.UUID `json:"tenant_id"`
	SiteID   uuid.UUID `json:"site_id"`
}

type GetEmailLogBodyStoredRow struct {
	ID         uuid.UUID `json:"id"`
	BodyStored bool      `json:"body_stored"`
}

// Fetch only the body_stored flag + id for a resend gate check.
func (q *Queries) GetEmailLogBodyStored(ctx context.Context, arg GetEmailLogBodyStoredParams) (GetEmailLogBodyStoredRow, error) {
	row := q.db.QueryRow(ctx, getEmailLogBodyStored, arg.ID, arg.TenantID, arg.SiteID)
	var i GetEmailLogBodyStoredRow
	err := row.Scan(&i.ID, &i.BodyStored)
	return i, err
}

const getEmailLogNext = `-- name: GetEmailLogNext :one
SELECT id
FROM site_email_log
WHERE tenant_id = $1
  AND site_id   = $2
  AND (created_at, id) > ($3::timestamptz, $4::uuid)
ORDER BY created_at ASC, id ASC
LIMIT 1
`

type GetEmailLogNextParams struct {
	TenantID uuid.UUID `json:"tenant_id"`
	SiteID   uuid.UUID `json:"site_id"`
	ThisTs   time.Time `json:"this_ts"`
	ThisID   uuid.UUID `json:"this_id"`
}

// Returns the id of the next-newer row for the Next button in detail navigation.
func (q *Queries) GetEmailLogNext(ctx context.Context, arg GetEmailLogNextParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, getEmailLogNext,
		arg.TenantID,
		arg.SiteID,
		arg.ThisTs,
		arg.ThisID,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const getEmailLogPrev = `-- name: GetEmailLogPrev :one
SELECT id
FROM site_email_log
WHERE tenant_id = $1
  AND site_id   = $2
  AND (created_at, id) < ($3::timestamptz, $4::uuid)
ORDER BY created_at DESC, id DESC
LIMIT 1
`

type GetEmailLogPrevParams struct {
	TenantID uuid.UUID `json:"tenant_id"`
	SiteID   uuid.UUID `json:"site_id"`
	ThisTs   time.Time `json:"this_ts"`
	ThisID   uuid.UUID `json:"this_id"`
}

// Returns the id of the next-older row for the Prev button in detail navigation.
func (q *Queries) GetEmailLogPrev(ctx context.Context, arg GetEmailLogPrevParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, getEmailLogPrev,
		arg.TenantID,
		arg.SiteID,
		arg.ThisTs,
		arg.ThisID,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const getEmailStats = `-- name: GetEmailStats :one
SELECT
    COUNT(*)                                          AS total,
    COUNT(*) FILTER (WHERE status = 'sent')           AS sent_count,
    COUNT(*) FILTER (WHERE status = 'failed')         AS failed_count,
    COUNT(DISTINCT provider)                          AS provider_count
FROM site_email_log
WHERE tenant_id   = $1
  AND site_id     = $2
  AND created_at >= $3
  AND created_at <= $4
`

type GetEmailStatsParams struct {
	TenantID  uuid.UUID `json:"tenant_id"`
	SiteID    uuid.UUID `json:"site_id"`
	RangeFrom time.Time `json:"range_from"`
	RangeTo   time.Time `json:"range_to"`
}

type GetEmailStatsRow struct {
	Total         int64 `json:"total"`
	SentCount     int64 `json:"sent_count"`
	FailedCount   int64 `json:"failed_count"`
	ProviderCount int64 `json:"provider_count"`
}

// Per-site summary: total sent/failed counts over [range_from, range_to].
// Repo always provides explicit bounds; use epoch-start + far-future as the
// open-ended defaults so no NULL handling is needed in SQL.
func (q *Queries) GetEmailStats(ctx context.Context, arg GetEmailStatsParams) (GetEmailStatsRow, error) {
	row := q.db.QueryRow(ctx, getEmailStats,
		arg.TenantID,
		arg.SiteID,
		arg.RangeFrom,
		arg.RangeTo,
	)
	var i GetEmailStatsRow
	err := row.Scan(
		&i.Total,
		&i.SentCount,
		&i.FailedCount,
		&i.ProviderCount,
	)
	return i, err
}

const getEmailStatsByDay = `-- name: GetEmailStatsByDay :many
SELECT
    date_trunc('day', created_at AT TIME ZONE 'UTC')::timestamptz AS day,
    COUNT(*)                                          AS total,
    COUNT(*) FILTER (WHERE status = 'sent')           AS sent_count,
    COUNT(*) FILTER (WHERE status = 'failed')         AS failed_count
FROM site_email_log
WHERE tenant_id   = $1
  AND site_id     = $2
  AND created_at >= $3
  AND created_at <= $4
GROUP BY 1
ORDER BY 1 ASC
`

type GetEmailStatsByDayParams struct {
	TenantID  uuid.UUID `json:"tenant_id"`
	SiteID    uuid.UUID `json:"site_id"`
	RangeFrom time.Time `json:"range_from"`
	RangeTo   time.Time `json:"range_to"`
}

type GetEmailStatsByDayRow struct {
	Day         time.Time `json:"day"`
	Total       int64     `json:"total"`
	SentCount   int64     `json:"sent_count"`
	FailedCount int64     `json:"failed_count"`
}

// Per-site daily time-series for the stats dashboard.
func (q *Queries) GetEmailStatsByDay(ctx context.Context, arg GetEmailStatsByDayParams) ([]GetEmailStatsByDayRow, error) {
	rows, err := q.db.Query(ctx, getEmailStatsByDay,
		arg.TenantID,
		arg.SiteID,
		arg.RangeFrom,
		arg.RangeTo,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetEmailStatsByDayRow
	for rows.Next() {
		var i GetEmailStatsByDayRow
		if err := rows.Scan(
			&i.Day,
			&i.Total,
			&i.SentCount,
			&i.FailedCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getEmailStatsByProvider = `-- name: GetEmailStatsByProvider :many
SELECT
    provider,
    COUNT(*)                                          AS total,
    COUNT(*) FILTER (WHERE status = 'sent')           AS sent_count,
    COUNT(*) FILTER (WHERE status = 'failed')         AS failed_count
FROM site_email_log
WHERE tenant_id   = $1
  AND site_id     = $2
  AND created_at >= $3
  AND created_at <= $4
GROUP BY provider
ORDER BY total DESC
`

type GetEmailStatsByProviderParams struct {
	TenantID  uuid.UUID `json:"tenant_id"`
	SiteID    uuid.UUID `json:"site_id"`
	RangeFrom time.Time `json:"range_from"`
	RangeTo   time.Time `json:"range_to"`
}

type GetEmailStatsByProviderRow struct {
	Provider    string `json:"provider"`
	Total       int64  `json:"total"`
	SentCount   int64  `json:"sent_count"`
	FailedCount int64  `json:"failed_count"`
}

// Per-site provider breakdown for the stats dashboard.
func (q *Queries) GetEmailStatsByProvider(ctx context.Context, arg GetEmailStatsByProviderParams) ([]GetEmailStatsByProviderRow, error) {
	rows, err := q.db.Query(ctx, getEmailStatsByProvider,
		arg.TenantID,
		arg.SiteID,
		arg.RangeFrom,
		arg.RangeTo,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetEmailStatsByProviderRow
	for rows.Next() {
		var i GetEmailStatsByProviderRow
		if err := rows.Scan(
			&i.Provider,
			&i.Total,
			&i.SentCount,
			&i.FailedCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getEmailSuppression = `-- name: GetEmailSuppression :one
SELECT id, tenant_id, site_id, email_hash, email, reason, provider, event_at, source_message_id, created_at
FROM email_suppression
WHERE id        = $1
  AND tenant_id = $2
`

type GetEmailSuppressionParams struct {
	ID       uuid.UUID `json:"id"`
	TenantID uuid.UUID `json:"tenant_id"`
}

// Fetch a single suppression entry by id (operator detail).
func (q *Queries) GetEmailSuppression(ctx context.Context, arg GetEmailSuppressionParams) (EmailSuppression, error) {
	row := q.db.QueryRow(ctx, getEmailSuppression, arg.ID, arg.TenantID)
	var i EmailSuppression
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.SiteID,
		&i.EmailHash,
		&i.Email,
		&i.Reason,
		&i.Provider,
		&i.EventAt,
		&i.SourceMessageID,
		&i.CreatedAt,
	)
	return i, err
}

const getFleetEmailStats = `-- name: GetFleetEmailStats :one
SELECT
    COUNT(*)                                          AS total,
    COUNT(*) FILTER (WHERE status = 'sent')           AS sent_count,
    COUNT(*) FILTER (WHERE status = 'failed')         AS failed_count,
    COUNT(DISTINCT provider)                          AS provider_count,
    COUNT(DISTINCT site_id)                           AS site_count
FROM site_email_log
WHERE tenant_id   = $1
  AND created_at >= $2
  AND created_at <= $3
`

type GetFleetEmailStatsParams struct {
	TenantID  uuid.UUID `json:"tenant_id"`
	RangeFrom time.Time `json:"range_from"`
	RangeTo   time.Time `json:"range_to"`
}

type GetFleetEmailStatsRow struct {
	Total         int64 `json:"total"`
	SentCount     int64 `json:"sent_count"`
	FailedCount   int64 `json:"failed_count"`
	ProviderCount int64 `json:"provider_count"`
	SiteCount     int64 `json:"site_count"`
}

// Tenant-wide summary (fleet dashboard).
func (q *Queries) GetFleetEmailStats(ctx context.Context, arg GetFleetEmailStatsParams) (GetFleetEmailStatsRow, error) {
	row := q.db.QueryRow(ctx, getFleetEmailStats, arg.TenantID, arg.RangeFrom, arg.RangeTo)
	var i GetFleetEmailStatsRow
	err := row.Scan(
		&i.Total,
		&i.SentCount,
		&i.FailedCount,
		&i.ProviderCount,
		&i.SiteCount,
	)
	return i, err
}

const getFleetEmailStatsByDay = `-- name: GetFleetEmailStatsByDay :many
SELECT
    date_trunc('day', created_at AT TIME ZONE 'UTC')::timestamptz AS day,
    COUNT(*)                                          AS total,
    COUNT(*) FILTER (WHERE status = 'sent')           AS sent_count,
    COUNT(*) FILTER (WHERE status = 'failed')         AS failed_count
FROM site_email_log
WHERE tenant_id   = $1
  AND created_at >= $2
  AND created_at <= $3
GROUP BY 1
ORDER BY 1 ASC
`

type GetFleetEmailStatsByDayParams struct {
	TenantID  uuid.UUID `json:"tenant_id"`
	RangeFrom time.Time `json:"range_from"`
	RangeTo   time.Time `json:"range_to"`
}

type GetFleetEmailStatsByDayRow struct {
	Day         time.Time `json:"day"`
	Total       int64     `json:"total"`
	SentCount   int64     `json:"sent_count"`
	FailedCount int64     `json:"failed_count"`
}

// Fleet daily time-series (tenant-wide).
func (q *Queries) GetFleetEmailStatsByDay(ctx context.Context, arg GetFleetEmailStatsByDayParams) ([]GetFleetEmailStatsByDayRow, error) {
	rows, err := q.db.Query(ctx, getFleetEmailStatsByDay, arg.TenantID, arg.RangeFrom, arg.RangeTo)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetFleetEmailStatsByDayRow
	for rows.Next() {
		var i GetFleetEmailStatsByDayRow
		if err := rows.Scan(
			&i.Day,
			&i.Total,
			&i.SentCount,
			&i.FailedCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getOrgEmailConfig = `-- name: GetOrgEmailConfig :one
SELECT id, tenant_id, site_id, provider, from_address, from_name, force_from_email, force_from_name, return_path, config, provider_secret_encrypted, oauth_refresh_encrypted, oauth_access_encrypted, oauth_expires_at, mappings, default_connection, fallback_connection, log_emails, store_body, retention_days, webhook_route_token_hash, webhook_signing_key_enc, ses_topic_arns, created_at, updated_at
FROM site_email_config
WHERE tenant_id = $1
  AND site_id IS NULL
`

// Returns the org-wide default config row (site_id IS NULL) for a tenant.
func (q *Queries) GetOrgEmailConfig(ctx context.Context, tenantID uuid.UUID) (SiteEmailConfig, error) {
	row := q.db.QueryRow(ctx, getOrgEmailConfig, tenantID)
	var i SiteEmailConfig
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.SiteID,
		&i.Provider,
		&i.FromAddress,
		&i.FromName,
		&i.ForceFromEmail,
		&i.ForceFromName,
		&i.ReturnPath,
		&i.Config,
		&i.ProviderSecretEncrypted,
		&i.OauthRefreshEncrypted,
		&i.OauthAccessEncrypted,
		&i.OauthExpiresAt,
		&i.Mappings,
		&i.DefaultConnection,
		&i.FallbackConnection,
		&i.LogEmails,
		&i.StoreBody,
		&i.RetentionDays,
		&i.WebhookRouteTokenHash,
		&i.WebhookSigningKeyEnc,
		&i.SesTopicArns,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSiteEmailConfig = `-- name: GetSiteEmailConfig :one


SELECT id, tenant_id, site_id, provider, from_address, from_name, force_from_email, force_from_name, return_path, config, provider_secret_encrypted, oauth_refresh_encrypted, oauth_access_encrypted, oauth_expires_at, mappings, default_connection, fallback_connection, log_emails, store_body, retention_days, webhook_route_token_hash, webhook_signing_key_enc, ses_topic_arns, created_at, updated_at
FROM site_email_config
WHERE tenant_id = $1
  AND site_id   = $2
`

type GetSiteEmailConfigParams struct {
	TenantID uuid.UUID   `json:"tenant_id"`
	SiteID   pgtype.UUID `json:"site_id"`
}

// M59 — Per-site Email / SMTP Management queries (Phase 1: config CRUD).
//
// All operator reads/writes run under pool.InTenantTx (app.tenant_id GUC).
// The repo NEVER returns provider_secret_encrypted to callers — only a
// secret_set boolean is surfaced (mirrors perf repo CDN credentials pattern).
// updated_at is set via now() in the query (no trigger).
// ---------------------------------------------------------------------------
// site_email_config
// ---------------------------------------------------------------------------
// Returns the per-site config row. Caller resolves org-wide inheritance in the
// service layer (call GetOrgEmailConfig when this returns pgx.ErrNoRows).
func (q *Queries) GetSiteEmailConfig(ctx context.Context, arg GetSiteEmailConfigParams) (SiteEmailConfig, error) {
	row := q.db.QueryRow(ctx, getSiteEmailConfig, arg.TenantID, arg.SiteID)
	var i SiteEmailConfig
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.SiteID,
		&i.Provider,
		&i.FromAddress,
		&i.FromName,
		&i.ForceFromEmail,
		&i.ForceFromName,
		&i.ReturnPath,
		&i.Config,
		&i.ProviderSecretEncrypted,
		&i.OauthRefreshEncrypted,
		&i.OauthAccessEncrypted,
		&i.OauthExpiresAt,
		&i.Mappings,
		&i.DefaultConnection,
		&i.FallbackConnection,
		&i.LogEmails,
		&i.StoreBody,
		&i.RetentionDays,
		&i.WebhookRouteTokenHash,
		&i.WebhookSigningKeyEnc,
		&i.SesTopicArns,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const incrEmailLogResentCount = `-- name: IncrEmailLogResentCount :exec
UPDATE site_email_log
SET resent_count = resent_count + 1,
    updated_at   = now()
WHERE id        = $1
  AND tenant_id = $2
  AND site_id   = $3
`

type IncrEmailLogResentCountParams struct {
	ID       uuid.UUID `json:"id"`
	TenantID uuid.UUID `json:"tenant_id"`
	SiteID   uuid.UUID `json:"site_id"`
}

// Increment resent_count on a specific log entry. Runs under InTenantTx.
func (q *Queries) IncrEmailLogResentCount(ctx context.Context, arg IncrEmailLogResentCountParams) error {
	_, err := q.db.Exec(ctx, incrEmailLogResentCount, arg.ID, arg.TenantID, arg.SiteID)
	return err
}

const ingestEmailLogEntry = `-- name: IngestEmailLogEntry :one

INSERT INTO site_email_log (
    tenant_id, site_id, agent_seq,
    message_id, to_addresses, from_address, subject, provider,
    status, response, error, retries, resent_count,
    body_stored, body,
    created_at, updated_at
) VALUES (
    $1, $2, $3,
    $4, $5, $6, $7, $8,
    $9, $10, $11, $12, $13,
    $14,
    -- Store body only when body_stored flag is set; otherwise NULL.
    CASE WHEN $14::boolean THEN $15::text ELSE NULL END,
    $16, now()
)
ON CONFLICT (tenant_id, site_id, agent_seq)
    WHERE agent_seq IS NOT NULL
DO UPDATE SET
    status        = EXCLUDED.status,
    response      = EXCLUDED.response,
    error         = EXCLUDED.error,
    resent_count  = EXCLUDED.resent_count,
    body_stored   = EXCLUDED.body_stored,
    body          = CASE WHEN EXCLUDED.body_stored THEN EXCLUDED.body ELSE site_email_log.body END,
    updated_at    = now()
RETURNING id, tenant_id, site_id, agent_seq, message_id, to_addresses, from_address, subject, provider, status, response, error, retries, resent_count, body_stored, body, created_at, updated_at
`

type IngestEmailLogEntryParams struct {
	TenantID    uuid.UUID `json:"tenant_id"`
	SiteID      uuid.UUID `json:"site_id"`
	AgentSeq    *int64    `json:"agent_seq"`
	MessageID   *string   `json:"message_id"`
	ToAddresses []string  `json:"to_addresses"`
	FromAddress string    `json:"from_address"`
	Subject     string    `json:"subject"`
	Provider    string    `json:"provider"`
	Status      string    `json:"status"`
	Response    []byte    `json:"response"`
	Error       string    `json:"error"`
	Retries     int32     `json:"retries"`
	ResentCount int32     `json:"resent_count"`
	BodyStored  bool      `json:"body_stored"`
	Body        string    `json:"body"`
	CreatedAt   time.Time `json:"created_at"`
}

// ---------------------------------------------------------------------------
// site_email_log  (Phase 3 — ingest + viewer)
// ---------------------------------------------------------------------------
// Idempotent upsert of one agent-pushed log entry keyed on
// (tenant_id, site_id, agent_seq). Status/response/error/resent_count may
// change on re-push (e.g. an asynchronous provider callback updates the
// status after initial delivery). Body is only stored when body_stored=true.
func (q *Queries) IngestEmailLogEntry(ctx context.Context, arg IngestEmailLogEntryParams) (SiteEmailLog, error) {
	row := q.db.QueryRow(ctx, ingestEmailLogEntry,
		arg.TenantID,
		arg.SiteID,
		arg.AgentSeq,
		arg.MessageID,
		arg.ToAddresses,
		arg.FromAddress,
		arg.Subject,
		arg.Provider,
		arg.Status,
		arg.Response,
		arg.Error,
		arg.Retries,
		arg.ResentCount,
		arg.BodyStored,
		arg.Body,
		arg.CreatedAt,
	)
	var i SiteEmailLog
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.SiteID,
		&i.AgentSeq,
		&i.MessageID,
		&i.ToAddresses,
		&i.FromAddress,
		&i.Subject,
		&i.Provider,
		&i.Status,
		&i.Response,
		&i.Error,
		&i.Retries,
		&i.ResentCount,
		&i.BodyStored,
		&i.Body,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertWebhookEventDedup = `-- name: InsertWebhookEventDedup :one

INSERT INTO email_webhook_events (
    provider_event_id, provider,
    tenant_id, site_id,
    email_hash, event_type, suppression_id
) VALUES (
    $1, $2,
    $3, $4,
    $5, $6, $7
)
ON CONFLICT (provider, provider_event_id) DO NOTHING
RETURNING id, provider_event_id, provider, tenant_id, site_id, email_hash, event_type, suppression_id, created_at
`

type InsertWebhookEventDedupParams struct {
	ProviderEventID string      `json:"provider_event_id"`
	Provider        string      `json:"provider"`
	TenantID        pgtype.UUID `json:"tenant_id"`
	SiteID          pgtype.UUID `json:"site_id"`
	EmailHash       []byte      `json:"email_hash"`
	EventType       string      `json:"event_type"`
	SuppressionID   pgtype.UUID `json:"suppression_id"`
}

// ---------------------------------------------------------------------------
// email_webhook_events  (Phase 4a — dedup / audit)
// ---------------------------------------------------------------------------
// Inserts a dedup sentinel for a provider event. Returns (row, inserted).
// ON CONFLICT DO NOTHING: if 0 rows are affected the event is a duplicate and
// must be dropped. Runs under InAgentTx (webhook path).
// m61: stores email_hash (SHA-256) instead of plaintext email (SHOULD-FIX #2).
func (q *Queries) InsertWebhookEventDedup(ctx context.Context, arg InsertWebhookEventDedupParams) (EmailWebhookEvent, error) {
	row := q.db.QueryRow(ctx, insertWebhookEventDedup,
		arg.ProviderEventID,
		arg.Provider,
		arg.TenantID,
		arg.SiteID,
		arg.EmailHash,
		arg.EventType,
		arg.SuppressionID,
	)
	var i EmailWebhookEvent
	err := row.Scan(
		&i.ID,
		&i.ProviderEventID,
		&i.Provider,
		&i.TenantID,
		&i.SiteID,
		&i.EmailHash,
		&i.EventType,
		&i.SuppressionID,
		&i.CreatedAt,
	)
	return i, err
}

const isSuppressed = `-- name: IsSuppressed :one
SELECT EXISTS (
    SELECT 1 FROM email_suppression
    WHERE tenant_id  = $1
      AND email_hash = $2
      AND (site_id IS NULL OR site_id = $3)
) AS suppressed
`

type IsSuppressedParams struct {
	TenantID  uuid.UUID   `json:"tenant_id"`
	EmailHash []byte      `json:"email_hash"`
	SiteID    pgtype.UUID `json:"site_id"`
}

// Returns true when the given email_hash is suppressed for this tenant at either
// the fleet level (site_id IS NULL) or the specific site.
// Runs under InAgentTx (pre-send check from the delta-fetch query) or InTenantTx.
func (q *Queries) IsSuppressed(ctx context.Context, arg IsSuppressedParams) (bool, error) {
	row := q.db.QueryRow(ctx, isSuppressed, arg.TenantID, arg.EmailHash, arg.SiteID)
	var suppressed bool
	err := row.Scan(&suppressed)
	return suppressed, err
}

const listEmailSuppression = `-- name: ListEmailSuppression :many
SELECT id, tenant_id, site_id, email_hash, email, reason, provider, event_at, source_message_id, created_at
FROM email_suppression
WHERE tenant_id = $1
  AND (
        ($2::boolean AND site_id IS NULL)
        OR site_id = $3
  )
  AND (created_at, id) < ($4::timestamptz, $5::uuid)
  AND ($6::text = '' OR reason = $6::text)
ORDER BY created_at DESC, id DESC
LIMIT $7
`

type ListEmailSuppressionParams struct {
	TenantID     uuid.UUID   `json:"tenant_id"`
	IncludeFleet bool        `json:"include_fleet"`
	SiteID       pgtype.UUID `json:"site_id"`
	CursorTs     time.Time   `json:"cursor_ts"`
	CursorID     uuid.UUID   `json:"cursor_id"`
	FilterReason string      `json:"filter_reason"`
	RowLimit     int32       `json:"row_limit"`
}

// Keyset-paginated list of suppression entries for a site.
// Pass site_id = uuid.Nil to list fleet-wide entries only (site_id IS NULL).
// Pass a real site_id to list that site's entries (plus fleet-wide entries).
// @include_fleet when true also returns fleet-wide (site_id IS NULL) rows.
// Ordered created_at DESC, id DESC (composite keyset; see wpmgr-keyset-cursor-composite).
func (q *Queries) ListEmailSuppression(ctx context.Context, arg ListEmailSuppressionParams) ([]EmailSuppression, error) {
	rows, err := q.db.Query(ctx, listEmailSuppression,
		arg.TenantID,
		arg.IncludeFleet,
		arg.SiteID,
		arg.CursorTs,
		arg.CursorID,
		arg.FilterReason,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []EmailSuppression
	for rows.Next() {
		var i EmailSuppression
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.SiteID,
			&i.EmailHash,
			&i.Email,
			&i.Reason,
			&i.Provider,
			&i.EventAt,
			&i.SourceMessageID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEmailSuppressionDeltas = `-- name: ListEmailSuppressionDeltas :many
SELECT id, tenant_id, site_id, email_hash, email, reason, provider, event_at, source_message_id, created_at
FROM email_suppression
WHERE tenant_id = $1
  AND (site_id IS NULL OR site_id = $2)
  AND (created_at, id) > ($3::timestamptz, $4::uuid)
ORDER BY created_at ASC, id ASC
LIMIT $5
`

type ListEmailSuppressionDeltasParams struct {
	TenantID uuid.UUID   `json:"tenant_id"`
	SiteID   pgtype.UUID `json:"site_id"`
	SinceTs  time.Time   `json:"since_ts"`
	SinceID  uuid.UUID   `json:"since_id"`
	RowLimit int32       `json:"row_limit"`
}

// Agent suppression-fetch: returns entries created after @since_id for
// the given tenant + site (including fleet-wide site_id IS NULL rows).
// Keyset cursor on (created_at, id) ASC (agent polls for new entries since last fetch).
// @since_ts / @since_id: last seen row; pass epoch-start + uuid-zero for the first fetch.
func (q *Queries) ListEmailSuppressionDeltas(ctx context.Context, arg ListEmailSuppressionDeltasParams) ([]EmailSuppression, error) {
	rows, err := q.db.Query(ctx, listEmailSuppressionDeltas,
		arg.TenantID,
		arg.SiteID,
		arg.SinceTs,
		arg.SinceID,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []EmailSuppression
	for rows.Next() {
		var i EmailSuppression
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.SiteID,
			&i.EmailHash,
			&i.Email,
			&i.Reason,
			&i.Provider,
			&i.EventAt,
			&i.SourceMessageID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFleetEmailLog = `-- name: ListFleetEmailLog :many
SELECT
    id, tenant_id, site_id, agent_seq,
    message_id, to_addresses, from_address, subject, provider,
    status, response, error, retries, resent_count,
    body_stored,
    created_at, updated_at
FROM site_email_log
WHERE tenant_id   = $1
  AND (created_at, id) < ($2::timestamptz, $3::uuid)
  AND ($4::text = '' OR status = $4::text)
  AND created_at >= $5
  AND created_at <= $6
  AND ($7::text = '' OR (
        subject ILIKE '%' || $7::text || '%'
        OR from_address ILIKE '%' || $7::text || '%'
  ))
ORDER BY created_at DESC, id DESC
LIMIT $8
`

type ListFleetEmailLogParams struct {
	TenantID     uuid.UUID `json:"tenant_id"`
	CursorTs     time.Time `json:"cursor_ts"`
	CursorID     uuid.UUID `json:"cursor_id"`
	FilterStatus string    `json:"filter_status"`
	RangeFrom    time.Time `json:"range_from"`
	RangeTo      time.Time `json:"range_to"`
	SearchQ      string    `json:"search_q"`
	RowLimit     int32     `json:"row_limit"`
}

type ListFleetEmailLogRow struct {
	ID          uuid.UUID `json:"id"`
	TenantID    uuid.UUID `json:"tenant_id"`
	SiteID      uuid.UUID `json:"site_id"`
	AgentSeq    *int64    `json:"agent_seq"`
	MessageID   *string   `json:"message_id"`
	ToAddresses []string  `json:"to_addresses"`
	FromAddress string    `json:"from_address"`
	Subject     string    `json:"subject"`
	Provider    string    `json:"provider"`
	Status      string    `json:"status"`
	Response    []byte    `json:"response"`
	Error       string    `json:"error"`
	Retries     int32     `json:"retries"`
	ResentCount int32     `json:"resent_count"`
	BodyStored  bool      `json:"body_stored"`
	CreatedAt   time.Time `json:"created_at"`
	UpdatedAt   time.Time `json:"updated_at"`
}

// Cross-site keyset-paginated list for a tenant (fleet/agency dashboard).
// Same composite cursor as ListSiteEmailLog. Body excluded from list.
// Repo passes sentinel epoch-start/@range_from and far-future/@range_to when no
// date filter is requested.
func (q *Queries) ListFleetEmailLog(ctx context.Context, arg ListFleetEmailLogParams) ([]ListFleetEmailLogRow, error) {
	rows, err := q.db.Query(ctx, listFleetEmailLog,
		arg.TenantID,
		arg.CursorTs,
		arg.CursorID,
		arg.FilterStatus,
		arg.RangeFrom,
		arg.RangeTo,
		arg.SearchQ,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListFleetEmailLogRow
	for rows.Next() {
		var i ListFleetEmailLogRow
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.SiteID,
			&i.AgentSeq,
			&i.MessageID,
			&i.ToAddresses,
			&i.FromAddress,
			&i.Subject,
			&i.Provider,
			&i.Status,
			&i.Response,
			&i.Error,
			&i.Retries,
			&i.ResentCount,
			&i.BodyStored,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFleetEmailSuppression = `-- name: ListFleetEmailSuppression :many
SELECT id, tenant_id, site_id, email_hash, email, reason, provider, event_at, source_message_id, created_at
FROM email_suppression
WHERE tenant_id = $1
  AND (created_at, id) < ($2::timestamptz, $3::uuid)
  AND ($4::text = '' OR reason = $4::text)
ORDER BY created_at DESC, id DESC
LIMIT $5
`

type ListFleetEmailSuppressionParams struct {
	TenantID     uuid.UUID `json:"tenant_id"`
	CursorTs     time.Time `json:"cursor_ts"`
	CursorID     uuid.UUID `json:"cursor_id"`
	FilterReason string    `json:"filter_reason"`
	RowLimit     int32     `json:"row_limit"`
}

// Fleet-scope list (no site filter). Returns all suppression entries for the
// tenant including both fleet-wide and per-site entries.
// Ordered created_at DESC, id DESC.
func (q *Queries) ListFleetEmailSuppression(ctx context.Context, arg ListFleetEmailSuppressionParams) ([]EmailSuppression, error) {
	rows, err := q.db.Query(ctx, listFleetEmailSuppression,
		arg.TenantID,
		arg.CursorTs,
		arg.CursorID,
		arg.FilterReason,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []EmailSuppression
	for rows.Next() {
		var i EmailSuppression
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.SiteID,
			&i.EmailHash,
			&i.Email,
			&i.Reason,
			&i.Provider,
			&i.EventAt,
			&i.SourceMessageID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSiteEmailConfigs = `-- name: ListSiteEmailConfigs :many
SELECT id, tenant_id, site_id, provider, from_address, from_name, force_from_email, force_from_name, return_path, config, provider_secret_encrypted, oauth_refresh_encrypted, oauth_access_encrypted, oauth_expires_at, mappings, default_connection, fallback_connection, log_emails, store_body, retention_days, webhook_route_token_hash, webhook_signing_key_enc, ses_topic_arns, created_at, updated_at
FROM site_email_config
WHERE tenant_id = $1
  AND site_id IS NOT NULL
ORDER BY created_at DESC, id DESC
LIMIT $3 OFFSET $2
`

type ListSiteEmailConfigsParams struct {
	TenantID  uuid.UUID `json:"tenant_id"`
	RowOffset int32     `json:"row_offset"`
	RowLimit  int32     `json:"row_limit"`
}

// Lists all per-site config rows for a tenant (dashboard overview).
// Excludes the org-wide default row (site_id IS NULL).
func (q *Queries) ListSiteEmailConfigs(ctx context.Context, arg ListSiteEmailConfigsParams) ([]SiteEmailConfig, error) {
	rows, err := q.db.Query(ctx, listSiteEmailConfigs, arg.TenantID, arg.RowOffset, arg.RowLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SiteEmailConfig
	for rows.Next() {
		var i SiteEmailConfig
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.SiteID,
			&i.Provider,
			&i.FromAddress,
			&i.FromName,
			&i.ForceFromEmail,
			&i.ForceFromName,
			&i.ReturnPath,
			&i.Config,
			&i.ProviderSecretEncrypted,
			&i.OauthRefreshEncrypted,
			&i.OauthAccessEncrypted,
			&i.OauthExpiresAt,
			&i.Mappings,
			&i.DefaultConnection,
			&i.FallbackConnection,
			&i.LogEmails,
			&i.StoreBody,
			&i.RetentionDays,
			&i.WebhookRouteTokenHash,
			&i.WebhookSigningKeyEnc,
			&i.SesTopicArns,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSiteEmailLog = `-- name: ListSiteEmailLog :many
SELECT
    id, tenant_id, site_id, agent_seq,
    message_id, to_addresses, from_address, subject, provider,
    status, response, error, retries, resent_count,
    body_stored,
    created_at, updated_at
FROM site_email_log
WHERE tenant_id   = $1
  AND site_id     = $2
  AND (created_at, id) < ($3::timestamptz, $4::uuid)
  AND ($5::text = '' OR status = $5::text)
  AND created_at >= $6
  AND created_at <= $7
  AND ($8::text = '' OR (
        subject ILIKE '%' || $8::text || '%'
        OR from_address ILIKE '%' || $8::text || '%'
        OR to_addresses::text ILIKE '%' || $8::text || '%'
  ))
ORDER BY created_at DESC, id DESC
LIMIT $9
`

type ListSiteEmailLogParams struct {
	TenantID     uuid.UUID `json:"tenant_id"`
	SiteID       uuid.UUID `json:"site_id"`
	CursorTs     time.Time `json:"cursor_ts"`
	CursorID     uuid.UUID `json:"cursor_id"`
	FilterStatus string    `json:"filter_status"`
	RangeFrom    time.Time `json:"range_from"`
	RangeTo      time.Time `json:"range_to"`
	SearchQ      string    `json:"search_q"`
	RowLimit     int32     `json:"row_limit"`
}

type ListSiteEmailLogRow struct {
	ID          uuid.UUID `json:"id"`
	TenantID    uuid.UUID `json:"tenant_id"`
	SiteID      uuid.UUID `json:"site_id"`
	AgentSeq    *int64    `json:"agent_seq"`
	MessageID   *string   `json:"message_id"`
	ToAddresses []string  `json:"to_addresses"`
	FromAddress string    `json:"from_address"`
	Subject     string    `json:"subject"`
	Provider    string    `json:"provider"`
	Status      string    `json:"status"`
	Response    []byte    `json:"response"`
	Error       string    `json:"error"`
	Retries     int32     `json:"retries"`
	ResentCount int32     `json:"resent_count"`
	BodyStored  bool      `json:"body_stored"`
	CreatedAt   time.Time `json:"created_at"`
	UpdatedAt   time.Time `json:"updated_at"`
}

// Keyset-paginated list for a single site. Ordered created_at DESC, id DESC.
// Composite (created_at, id) cursor predicate avoids skipping co-timestamped
// rows (batch inserts share created_at — see wpmgr-keyset-cursor-composite).
// Body is intentionally excluded from the list — callers use GetEmailLog for detail.
// @cursor_ts and @cursor_id are the last row's created_at/id; pass far-future
// values (e.g. now()+100yr, max-uuid) to get the first page.
// Repo passes sentinel epoch-start/@range_from and far-future/@range_to when no
// date filter is requested; @filter_status ” skips the status filter;
// @search_q ” skips the text search.
func (q *Queries) ListSiteEmailLog(ctx context.Context, arg ListSiteEmailLogParams) ([]ListSiteEmailLogRow, error) {
	rows, err := q.db.Query(ctx, listSiteEmailLog,
		arg.TenantID,
		arg.SiteID,
		arg.CursorTs,
		arg.CursorID,
		arg.FilterStatus,
		arg.RangeFrom,
		arg.RangeTo,
		arg.SearchQ,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSiteEmailLogRow
	for rows.Next() {
		var i ListSiteEmailLogRow
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.SiteID,
			&i.AgentSeq,
			&i.MessageID,
			&i.ToAddresses,
			&i.FromAddress,
			&i.Subject,
			&i.Provider,
			&i.Status,
			&i.Response,
			&i.Error,
			&i.Retries,
			&i.ResentCount,
			&i.BodyStored,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markEmailLogBounced = `-- name: MarkEmailLogBounced :exec

UPDATE site_email_log
SET status     = $1,
    updated_at = now()
WHERE message_id = $2
  AND tenant_id  = $3
  AND site_id    = $4
`

type MarkEmailLogBouncedParams struct {
	Status    string    `json:"status"`
	MessageID *string   `json:"message_id"`
	TenantID  uuid.UUID `json:"tenant_id"`
	SiteID    uuid.UUID `json:"site_id"`
}

// ---------------------------------------------------------------------------
// site_email_log  Phase 4a additions
// ---------------------------------------------------------------------------
// Update a log entry's status to 'bounced' or 'complained' when a webhook
// event arrives. Matched by message_id + tenant_id + site_id.
// m61 SHOULD-FIX #3: site_id added so a colliding message_id from a different
// site in the same tenant cannot flip another site's row.
// Runs under InAgentTx; tenant_id provided for defense-in-depth in addition to
// RLS; site_id added to narrow the update scope.
func (q *Queries) MarkEmailLogBounced(ctx context.Context, arg MarkEmailLogBouncedParams) error {
	_, err := q.db.Exec(ctx, markEmailLogBounced,
		arg.Status,
		arg.MessageID,
		arg.TenantID,
		arg.SiteID,
	)
	return err
}

const pruneWebhookEventDedup = `-- name: PruneWebhookEventDedup :execrows
DELETE FROM email_webhook_events
WHERE created_at < $1::timestamptz
`

// Prune dedup rows older than the given cutoff (run by the GC worker).
// Cross-tenant / InAgentTx.
func (q *Queries) PruneWebhookEventDedup(ctx context.Context, cutoffTs time.Time) (int64, error) {
	result, err := q.db.Exec(ctx, pruneWebhookEventDedup, cutoffTs)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setEmailConfigWebhookFields = `-- name: SetEmailConfigWebhookFields :one
UPDATE site_email_config
SET webhook_route_token_hash = $1::bytea,
    ses_topic_arns            = $2::text[],
    webhook_signing_key_enc   = CASE WHEN $3::boolean
                                    THEN $4::bytea
                                    ELSE webhook_signing_key_enc END,
    updated_at                = now()
WHERE tenant_id = $5
  AND id        = $6
RETURNING id, tenant_id, site_id, provider, from_address, from_name, force_from_email, force_from_name, return_path, config, provider_secret_encrypted, oauth_refresh_encrypted, oauth_access_encrypted, oauth_expires_at, mappings, default_connection, fallback_connection, log_emails, store_body, retention_days, webhook_route_token_hash, webhook_signing_key_enc, ses_topic_arns, created_at, updated_at
`

type SetEmailConfigWebhookFieldsParams struct {
	TokenHash     []byte    `json:"token_hash"`
	SesTopicArns  []string  `json:"ses_topic_arns"`
	SetSigningKey bool      `json:"set_signing_key"`
	SigningKeyEnc []byte    `json:"signing_key_enc"`
	TenantID      uuid.UUID `json:"tenant_id"`
	ID            uuid.UUID `json:"id"`
}

// m61: write/rotate webhook security columns on a config row.
// Use set_signing_key flag (nil-sentinel) to preserve the existing encrypted key
// when rotating only the token or ARNs.
// Runs under InTenantTx (operator PUT path).
func (q *Queries) SetEmailConfigWebhookFields(ctx context.Context, arg SetEmailConfigWebhookFieldsParams) (SiteEmailConfig, error) {
	row := q.db.QueryRow(ctx, setEmailConfigWebhookFields,
		arg.TokenHash,
		arg.SesTopicArns,
		arg.SetSigningKey,
		arg.SigningKeyEnc,
		arg.TenantID,
		arg.ID,
	)
	var i SiteEmailConfig
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.SiteID,
		&i.Provider,
		&i.FromAddress,
		&i.FromName,
		&i.ForceFromEmail,
		&i.ForceFromName,
		&i.ReturnPath,
		&i.Config,
		&i.ProviderSecretEncrypted,
		&i.OauthRefreshEncrypted,
		&i.OauthAccessEncrypted,
		&i.OauthExpiresAt,
		&i.Mappings,
		&i.DefaultConnection,
		&i.FallbackConnection,
		&i.LogEmails,
		&i.StoreBody,
		&i.RetentionDays,
		&i.WebhookRouteTokenHash,
		&i.WebhookSigningKeyEnc,
		&i.SesTopicArns,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertEmailSuppression = `-- name: UpsertEmailSuppression :one

INSERT INTO email_suppression (
    tenant_id, site_id,
    email_hash, email,
    reason, provider, event_at, source_message_id
) VALUES (
    $1, $2,
    $3, $4,
    $5, $6, $7, $8
)
ON CONFLICT (tenant_id, site_id, email_hash)
    WHERE site_id IS NOT NULL
DO UPDATE SET
    reason            = EXCLUDED.reason,
    provider          = EXCLUDED.provider,
    event_at          = EXCLUDED.event_at,
    source_message_id = EXCLUDED.source_message_id
RETURNING id, tenant_id, site_id, email_hash, email, reason, provider, event_at, source_message_id, created_at
`

type UpsertEmailSuppressionParams struct {
	TenantID        uuid.UUID          `json:"tenant_id"`
	SiteID          pgtype.UUID        `json:"site_id"`
	EmailHash       []byte             `json:"email_hash"`
	Email           *string            `json:"email"`
	Reason          string             `json:"reason"`
	Provider        string             `json:"provider"`
	EventAt         pgtype.Timestamptz `json:"event_at"`
	SourceMessageID *string            `json:"source_message_id"`
}

// ---------------------------------------------------------------------------
// email_suppression  (Phase 4a — webhooks + suppression list)
// ---------------------------------------------------------------------------
// Insert-or-ignore for one email suppression entry keyed on
// (tenant_id, COALESCE(site_id,'00000000-0000-0000-0000-000000000000'), email_hash).
// The two partial unique indexes enforce the uniqueness separately for per-site
// and fleet-wide (site_id IS NULL) rows. ON CONFLICT DO UPDATE refreshes the
// mutable fields so a duplicate bounce from a different provider still records
// the most recent provider + event_at.
// Runs under InAgentTx (webhook path) or InTenantTx (operator manual-add).
func (q *Queries) UpsertEmailSuppression(ctx context.Context, arg UpsertEmailSuppressionParams) (EmailSuppression, error) {
	row := q.db.QueryRow(ctx, upsertEmailSuppression,
		arg.TenantID,
		arg.SiteID,
		arg.EmailHash,
		arg.Email,
		arg.Reason,
		arg.Provider,
		arg.EventAt,
		arg.SourceMessageID,
	)
	var i EmailSuppression
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.SiteID,
		&i.EmailHash,
		&i.Email,
		&i.Reason,
		&i.Provider,
		&i.EventAt,
		&i.SourceMessageID,
		&i.CreatedAt,
	)
	return i, err
}

const upsertEmailSuppressionFleet = `-- name: UpsertEmailSuppressionFleet :one
INSERT INTO email_suppression (
    tenant_id, site_id,
    email_hash, email,
    reason, provider, event_at, source_message_id
) VALUES (
    $1, NULL,
    $2, $3,
    $4, $5, $6, $7
)
ON CONFLICT (tenant_id, email_hash)
    WHERE site_id IS NULL
DO UPDATE SET
    reason            = EXCLUDED.reason,
    provider          = EXCLUDED.provider,
    event_at          = EXCLUDED.event_at,
    source_message_id = EXCLUDED.source_message_id
RETURNING id, tenant_id, site_id, email_hash, email, reason, provider, event_at, source_message_id, created_at
`

type UpsertEmailSuppressionFleetParams struct {
	TenantID        uuid.UUID          `json:"tenant_id"`
	EmailHash       []byte             `json:"email_hash"`
	Email           *string            `json:"email"`
	Reason          string             `json:"reason"`
	Provider        string             `json:"provider"`
	EventAt         pgtype.Timestamptz `json:"event_at"`
	SourceMessageID *string            `json:"source_message_id"`
}

// Fleet-wide (site_id IS NULL) variant — separate query because the conflict
// target differs (the fleet-wide partial index has no site_id column).
func (q *Queries) UpsertEmailSuppressionFleet(ctx context.Context, arg UpsertEmailSuppressionFleetParams) (EmailSuppression, error) {
	row := q.db.QueryRow(ctx, upsertEmailSuppressionFleet,
		arg.TenantID,
		arg.EmailHash,
		arg.Email,
		arg.Reason,
		arg.Provider,
		arg.EventAt,
		arg.SourceMessageID,
	)
	var i EmailSuppression
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.SiteID,
		&i.EmailHash,
		&i.Email,
		&i.Reason,
		&i.Provider,
		&i.EventAt,
		&i.SourceMessageID,
		&i.CreatedAt,
	)
	return i, err
}

const upsertOrgEmailConfig = `-- name: UpsertOrgEmailConfig :one
INSERT INTO site_email_config (
    tenant_id, site_id,
    provider,
    from_address, from_name, force_from_email, force_from_name, return_path,
    config,
    provider_secret_encrypted,
    mappings, default_connection, fallback_connection,
    log_emails, store_body, retention_days,
    updated_at
) VALUES (
    $1, NULL,
    $2,
    $3, $4, $5, $6, $7,
    $8,
    CASE WHEN $9::boolean THEN $10::bytea ELSE NULL END,
    $11, $12, $13,
    $14, $15, $16,
    now()
)
ON CONFLICT (tenant_id) WHERE site_id IS NULL
DO UPDATE SET
    provider                  = EXCLUDED.provider,
    from_address              = EXCLUDED.from_address,
    from_name                 = EXCLUDED.from_name,
    force_from_email          = EXCLUDED.force_from_email,
    force_from_name           = EXCLUDED.force_from_name,
    return_path               = EXCLUDED.return_path,
    config                    = EXCLUDED.config,
    provider_secret_encrypted = CASE WHEN $9::boolean
                                    THEN EXCLUDED.provider_secret_encrypted
                                    ELSE site_email_config.provider_secret_encrypted END,
    mappings                  = EXCLUDED.mappings,
    default_connection        = EXCLUDED.default_connection,
    fallback_connection       = EXCLUDED.fallback_connection,
    log_emails                = EXCLUDED.log_emails,
    store_body                = EXCLUDED.store_body,
    retention_days            = EXCLUDED.retention_days,
    updated_at                = now()
RETURNING id, tenant_id, site_id, provider, from_address, from_name, force_from_email, force_from_name, return_path, config, provider_secret_encrypted, oauth_refresh_encrypted, oauth_access_encrypted, oauth_expires_at, mappings, default_connection, fallback_connection, log_emails, store_body, retention_days, webhook_route_token_hash, webhook_signing_key_enc, ses_topic_arns, created_at, updated_at
`

type UpsertOrgEmailConfigParams struct {
	TenantID                uuid.UUID `json:"tenant_id"`
	Provider                string    `json:"provider"`
	FromAddress             string    `json:"from_address"`
	FromName                string    `json:"from_name"`
	ForceFromEmail          bool      `json:"force_from_email"`
	ForceFromName           bool      `json:"force_from_name"`
	ReturnPath              bool      `json:"return_path"`
	Config                  []byte    `json:"config"`
	SetSecret               bool      `json:"set_secret"`
	ProviderSecretEncrypted []byte    `json:"provider_secret_encrypted"`
	Mappings                []byte    `json:"mappings"`
	DefaultConnection       *string   `json:"default_connection"`
	FallbackConnection      *string   `json:"fallback_connection"`
	LogEmails               bool      `json:"log_emails"`
	StoreBody               bool      `json:"store_body"`
	RetentionDays           int32     `json:"retention_days"`
}

// Upsert the org-wide default row (site_id IS NULL).
func (q *Queries) UpsertOrgEmailConfig(ctx context.Context, arg UpsertOrgEmailConfigParams) (SiteEmailConfig, error) {
	row := q.db.QueryRow(ctx, upsertOrgEmailConfig,
		arg.TenantID,
		arg.Provider,
		arg.FromAddress,
		arg.FromName,
		arg.ForceFromEmail,
		arg.ForceFromName,
		arg.ReturnPath,
		arg.Config,
		arg.SetSecret,
		arg.ProviderSecretEncrypted,
		arg.Mappings,
		arg.DefaultConnection,
		arg.FallbackConnection,
		arg.LogEmails,
		arg.StoreBody,
		arg.RetentionDays,
	)
	var i SiteEmailConfig
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.SiteID,
		&i.Provider,
		&i.FromAddress,
		&i.FromName,
		&i.ForceFromEmail,
		&i.ForceFromName,
		&i.ReturnPath,
		&i.Config,
		&i.ProviderSecretEncrypted,
		&i.OauthRefreshEncrypted,
		&i.OauthAccessEncrypted,
		&i.OauthExpiresAt,
		&i.Mappings,
		&i.DefaultConnection,
		&i.FallbackConnection,
		&i.LogEmails,
		&i.StoreBody,
		&i.RetentionDays,
		&i.WebhookRouteTokenHash,
		&i.WebhookSigningKeyEnc,
		&i.SesTopicArns,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertSiteEmailConfig = `-- name: UpsertSiteEmailConfig :one
INSERT INTO site_email_config (
    tenant_id, site_id,
    provider,
    from_address, from_name, force_from_email, force_from_name, return_path,
    config,
    provider_secret_encrypted,
    mappings, default_connection, fallback_connection,
    log_emails, store_body, retention_days,
    updated_at
) VALUES (
    $1, $2,
    $3,
    $4, $5, $6, $7, $8,
    $9,
    -- ::bytea so Postgres can infer the param type (both CASE branches are
    -- otherwise untyped: a bare param + NULL -> "could not determine data type").
    CASE WHEN $10::boolean THEN $11::bytea ELSE NULL END,
    $12, $13, $14,
    $15, $16, $17,
    now()
)
ON CONFLICT ON CONSTRAINT site_email_config_pkey DO NOTHING
RETURNING id, tenant_id, site_id, provider, from_address, from_name, force_from_email, force_from_name, return_path, config, provider_secret_encrypted, oauth_refresh_encrypted, oauth_access_encrypted, oauth_expires_at, mappings, default_connection, fallback_connection, log_emails, store_body, retention_days, webhook_route_token_hash, webhook_signing_key_enc, ses_topic_arns, created_at, updated_at
`

type UpsertSiteEmailConfigParams struct {
	TenantID                uuid.UUID   `json:"tenant_id"`
	SiteID                  pgtype.UUID `json:"site_id"`
	Provider                string      `json:"provider"`
	FromAddress             string      `json:"from_address"`
	FromName                string      `json:"from_name"`
	ForceFromEmail          bool        `json:"force_from_email"`
	ForceFromName           bool        `json:"force_from_name"`
	ReturnPath              bool        `json:"return_path"`
	Config                  []byte      `json:"config"`
	SetSecret               bool        `json:"set_secret"`
	ProviderSecretEncrypted []byte      `json:"provider_secret_encrypted"`
	Mappings                []byte      `json:"mappings"`
	DefaultConnection       *string     `json:"default_connection"`
	FallbackConnection      *string     `json:"fallback_connection"`
	LogEmails               bool        `json:"log_emails"`
	StoreBody               bool        `json:"store_body"`
	RetentionDays           int32       `json:"retention_days"`
}

// Insert-or-update a per-site config row. provider_secret_encrypted uses a
// nil-sentinel: when @set_secret is false the existing ciphertext is preserved,
// so editing non-secret fields without re-entering the password keeps the stored
// secret intact (mirrors smtp_settings.sql UpsertSMTPSettings pattern exactly).
func (q *Queries) UpsertSiteEmailConfig(ctx context.Context, arg UpsertSiteEmailConfigParams) (SiteEmailConfig, error) {
	row := q.db.QueryRow(ctx, upsertSiteEmailConfig,
		arg.TenantID,
		arg.SiteID,
		arg.Provider,
		arg.FromAddress,
		arg.FromName,
		arg.ForceFromEmail,
		arg.ForceFromName,
		arg.ReturnPath,
		arg.Config,
		arg.SetSecret,
		arg.ProviderSecretEncrypted,
		arg.Mappings,
		arg.DefaultConnection,
		arg.FallbackConnection,
		arg.LogEmails,
		arg.StoreBody,
		arg.RetentionDays,
	)
	var i SiteEmailConfig
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.SiteID,
		&i.Provider,
		&i.FromAddress,
		&i.FromName,
		&i.ForceFromEmail,
		&i.ForceFromName,
		&i.ReturnPath,
		&i.Config,
		&i.ProviderSecretEncrypted,
		&i.OauthRefreshEncrypted,
		&i.OauthAccessEncrypted,
		&i.OauthExpiresAt,
		&i.Mappings,
		&i.DefaultConnection,
		&i.FallbackConnection,
		&i.LogEmails,
		&i.StoreBody,
		&i.RetentionDays,
		&i.WebhookRouteTokenHash,
		&i.WebhookSigningKeyEnc,
		&i.SesTopicArns,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertSiteEmailConfigByTenantSite = `-- name: UpsertSiteEmailConfigByTenantSite :one
INSERT INTO site_email_config (
    tenant_id, site_id,
    provider,
    from_address, from_name, force_from_email, force_from_name, return_path,
    config,
    provider_secret_encrypted,
    mappings, default_connection, fallback_connection,
    log_emails, store_body, retention_days,
    updated_at
) VALUES (
    $1, $2,
    $3,
    $4, $5, $6, $7, $8,
    $9,
    CASE WHEN $10::boolean THEN $11::bytea ELSE NULL END,
    $12, $13, $14,
    $15, $16, $17,
    now()
)
ON CONFLICT (tenant_id, site_id) WHERE site_id IS NOT NULL
DO UPDATE SET
    provider                  = EXCLUDED.provider,
    from_address              = EXCLUDED.from_address,
    from_name                 = EXCLUDED.from_name,
    force_from_email          = EXCLUDED.force_from_email,
    force_from_name           = EXCLUDED.force_from_name,
    return_path               = EXCLUDED.return_path,
    config                    = EXCLUDED.config,
    provider_secret_encrypted = CASE WHEN $10::boolean
                                    THEN EXCLUDED.provider_secret_encrypted
                                    ELSE site_email_config.provider_secret_encrypted END,
    mappings                  = EXCLUDED.mappings,
    default_connection        = EXCLUDED.default_connection,
    fallback_connection       = EXCLUDED.fallback_connection,
    log_emails                = EXCLUDED.log_emails,
    store_body                = EXCLUDED.store_body,
    retention_days            = EXCLUDED.retention_days,
    updated_at                = now()
RETURNING id, tenant_id, site_id, provider, from_address, from_name, force_from_email, force_from_name, return_path, config, provider_secret_encrypted, oauth_refresh_encrypted, oauth_access_encrypted, oauth_expires_at, mappings, default_connection, fallback_connection, log_emails, store_body, retention_days, webhook_route_token_hash, webhook_signing_key_enc, ses_topic_arns, created_at, updated_at
`

type UpsertSiteEmailConfigByTenantSiteParams struct {
	TenantID                uuid.UUID   `json:"tenant_id"`
	SiteID                  pgtype.UUID `json:"site_id"`
	Provider                string      `json:"provider"`
	FromAddress             string      `json:"from_address"`
	FromName                string      `json:"from_name"`
	ForceFromEmail          bool        `json:"force_from_email"`
	ForceFromName           bool        `json:"force_from_name"`
	ReturnPath              bool        `json:"return_path"`
	Config                  []byte      `json:"config"`
	SetSecret               bool        `json:"set_secret"`
	ProviderSecretEncrypted []byte      `json:"provider_secret_encrypted"`
	Mappings                []byte      `json:"mappings"`
	DefaultConnection       *string     `json:"default_connection"`
	FallbackConnection      *string     `json:"fallback_connection"`
	LogEmails               bool        `json:"log_emails"`
	StoreBody               bool        `json:"store_body"`
	RetentionDays           int32       `json:"retention_days"`
}

// Upsert variant that matches on (tenant_id, site_id) instead of PK — used for
// the standard per-site PUT where no id is known by the caller.
// For the org-wide default (site_id IS NULL) use UpsertOrgEmailConfig instead.
func (q *Queries) UpsertSiteEmailConfigByTenantSite(ctx context.Context, arg UpsertSiteEmailConfigByTenantSiteParams) (SiteEmailConfig, error) {
	row := q.db.QueryRow(ctx, upsertSiteEmailConfigByTenantSite,
		arg.TenantID,
		arg.SiteID,
		arg.Provider,
		arg.FromAddress,
		arg.FromName,
		arg.ForceFromEmail,
		arg.ForceFromName,
		arg.ReturnPath,
		arg.Config,
		arg.SetSecret,
		arg.ProviderSecretEncrypted,
		arg.Mappings,
		arg.DefaultConnection,
		arg.FallbackConnection,
		arg.LogEmails,
		arg.StoreBody,
		arg.RetentionDays,
	)
	var i SiteEmailConfig
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.SiteID,
		&i.Provider,
		&i.FromAddress,
		&i.FromName,
		&i.ForceFromEmail,
		&i.ForceFromName,
		&i.ReturnPath,
		&i.Config,
		&i.ProviderSecretEncrypted,
		&i.OauthRefreshEncrypted,
		&i.OauthAccessEncrypted,
		&i.OauthExpiresAt,
		&i.Mappings,
		&i.DefaultConnection,
		&i.FallbackConnection,
		&i.LogEmails,
		&i.StoreBody,
		&i.RetentionDays,
		&i.WebhookRouteTokenHash,
		&i.WebhookSigningKeyEnc,
		&i.SesTopicArns,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
