// Package twofactor defines the SecondFactor interface and the supporting
// types used by both TOTP and WebAuthn implementations. The login and
// management handlers program to this interface so that adding a new factor
// type (e.g. SMS) requires only a new implementor, not changes to the
// orchestrating service layer.
//
// Phase 1 (ADR-056) ships the interface, the Config + WebAuthn constructor,
// and skeleton implementors. Ceremony logic (BeginLogin, FinishLogin, etc.)
// is added in Phase 2 when the service methods are wired.
package twofactor

import (
	"context"
	"strings"

	"github.com/go-webauthn/webauthn/webauthn"
	"github.com/google/uuid"
)

// SecondFactor abstracts a second-factor authenticator type so that the login
// and enrollment flows are factor-agnostic. Both TOTP and WebAuthn implement
// this interface. A future SMS or email-OTP factor would implement it too.
//
// The interface is intentionally thin: factor-specific state (TOTP secret,
// WebAuthn credential IDs, go-webauthn SessionData) is persisted by the
// service layer via the sqlc-generated queries, not inside the implementor.
// The implementor is stateless and can be shared across goroutines.
type SecondFactor interface {
	// Kind returns the discriminator for this factor type:
	// "totp" or "webauthn". Stored in two_factor_challenges.kind.
	Kind() string

	// BeginLogin issues a challenge for the given user. The returned
	// challengeMeta is factor-specific:
	//   TOTP:     nil (challenge nonce is generated by the service layer; TOTP
	//             has no server-side challenge to issue).
	//   WebAuthn: *webauthn.SessionData (go-webauthn assertion options +
	//             session; JSON-serialised into two_factor_challenges.webauthn_session).
	//
	// The service layer persists the challengeMeta and supplies it back to
	// FinishLogin after the client responds.
	BeginLogin(ctx context.Context, userID uuid.UUID) (challengeMeta any, err error)

	// FinishLogin verifies the user's response to a challenge.
	//   clientData: factor-specific response bytes from the client.
	//     TOTP:     6-digit ASCII string (e.g. "123456").
	//     WebAuthn: raw JSON of the authenticator assertion response.
	//   challengeMeta: the value returned by BeginLogin (nil for TOTP).
	//
	// Returns nil on success. Returns a typed domain error on failure so the
	// handler can map it to the correct HTTP status.
	FinishLogin(ctx context.Context, userID uuid.UUID, challengeMeta any, clientData []byte) error

	// BeginRegistration starts enrollment for the given user. Returns setup
	// data to be shown to / consumed by the client:
	//   TOTP:     *TOTPSetup (otpauth URI + base32 secret).
	//   WebAuthn: *webauthn.Protocol.CredentialCreation JSON bytes.
	//
	// The setup data is NOT yet persisted; it is only committed by
	// FinishRegistration after the client proves possession.
	BeginRegistration(ctx context.Context, userID uuid.UUID, userEmail string) (setupData any, err error)

	// FinishRegistration verifies the enrollment response and persists the
	// new credential. On success the factor is considered enrolled for the
	// user (the caller updates users.two_factor_enabled).
	//   setupData:  the value returned by BeginRegistration.
	//   clientData: factor-specific response bytes from the client.
	//     TOTP:     6-digit ASCII verification code.
	//     WebAuthn: raw JSON of the authenticator attestation response.
	FinishRegistration(ctx context.Context, userID uuid.UUID, setupData any, clientData []byte) error
}

// TOTPSetup is the setup payload returned by the TOTP implementor's
// BeginRegistration. The frontend renders the QR from OtpAuthURI and displays
// Secret as a manual-entry fallback. Neither field is persisted until the
// user verifies a live code (FinishRegistration).
type TOTPSetup struct {
	// OtpAuthURI is the otpauth://totp/... URI for QR rendering client-side.
	OtpAuthURI string
	// Secret is the base32-encoded shared secret for manual authenticator entry.
	// Shown once during enrollment; never returned by the API again afterwards.
	Secret string
}

// Config holds the configuration needed to construct the WebAuthn relying
// party. Fields are populated from AuthConfig (internal/config/config.go).
//
// For the hosted WPMgr instance the defaults cover everything. Self-hosted
// operators must set RPID and RPOrigins to match their public URL.
type Config struct {
	// RPID is the effective domain (e.g. "manage.wpmgr.app" or "myhost.example.com").
	// This MUST match the origin's eTLD+1 that browsers use for WebAuthn.
	RPID string
	// RPOrigins is the list of fully-qualified origins allowed for WebAuthn
	// ceremonies (e.g. ["https://manage.wpmgr.app"]).
	// Parsed from a comma-separated config string.
	RPOrigins []string
	// RPDisplayName is the human-readable site name shown in passkey prompts.
	RPDisplayName string
}

// ParseRPOrigins splits a comma-separated origin string into a slice, trimming
// whitespace. An empty string returns nil (go-webauthn treats nil as
// unconstrained; callers should always supply at least one origin).
func ParseRPOrigins(csv string) []string {
	if csv == "" {
		return nil
	}
	parts := strings.Split(csv, ",")
	out := make([]string, 0, len(parts))
	for _, p := range parts {
		if s := strings.TrimSpace(p); s != "" {
			out = append(out, s)
		}
	}
	return out
}

// NewWebAuthn builds a go-webauthn *webauthn.WebAuthn from a Config. The
// returned instance is used by the WebAuthn implementor for both registration
// and assertion ceremonies. It is safe to share across goroutines.
//
// Returns an error if the go-webauthn library rejects the configuration
// (e.g. empty RPID or malformed origin). Callers should call this once at
// application startup and treat an error as a fatal misconfiguration.
func NewWebAuthn(cfg Config) (*webauthn.WebAuthn, error) {
	wc := &webauthn.Config{
		RPID:          cfg.RPID,
		RPDisplayName: cfg.RPDisplayName,
		RPOrigins:     cfg.RPOrigins,
	}
	return webauthn.New(wc)
}
