"use client";

import { cn } from "@/lib/utils";

// Illustrative white-label client report preview widget for the client-reports page.
// Sample data only.

const SECTIONS = [
  { label: "Uptime", value: "99.9%", detail: "0 incidents this month", tone: "success" },
  { label: "Backups", value: "28/28", detail: "Last: 2 hours ago", tone: "success" },
  { label: "Updates", value: "14 applied", detail: "0 pending", tone: "success" },
  { label: "Core Web Vitals", value: "LCP 1.8s", detail: "p75 from real visitors", tone: "primary" },
  { label: "Email delivery", value: "98.4%", detail: "1 bounce suppressed", tone: "warn" },
] as const;

const TONE: Record<string, { value: string; badge: string }> = {
  success: {
    value: "text-[var(--success)]",
    badge: "bg-[var(--success)]/12 text-[var(--success)]",
  },
  primary: {
    value: "text-[var(--primary)]",
    badge: "bg-[var(--primary-subtle)] text-[var(--primary-pressed)]",
  },
  warn: {
    value: "text-[var(--warning-subtle-fg)]",
    badge: "bg-[var(--warning-subtle-fg)]/12 text-[var(--warning-subtle-fg)]",
  },
};

export function ClientReportsVisual() {
  return (
    <div className="flex flex-col gap-0 overflow-hidden rounded-xl border border-[var(--border)] bg-card shadow-sm">
      {/* Report header (branded) */}
      <div
        className="flex items-center gap-3 border-b border-[var(--border)] px-5 py-3"
        style={{ background: "var(--primary-subtle)" }}
      >
        <div className="h-7 w-7 rounded-md bg-[var(--primary)] flex items-center justify-center">
          <span className="font-mono text-[10px] font-bold text-[var(--primary-foreground)]">AC</span>
        </div>
        <div className="flex-1 min-w-0">
          <p className="text-xs font-semibold text-foreground leading-tight">Acme Web Agency</p>
          <p className="text-[10px] text-[var(--muted-foreground)]">Monthly maintenance report &bull; June 2026</p>
        </div>
        <span className="shrink-0 rounded-full bg-[var(--primary)]/15 px-2 py-0.5 text-[10px] font-semibold text-[var(--primary-pressed)]">
          shop.client.com
        </span>
      </div>

      {/* Report body */}
      <div className="flex flex-col gap-0">
        {SECTIONS.map((section, i) => {
          const t = TONE[section.tone];
          return (
            <div
              key={section.label}
              className={cn(
                "flex items-center gap-4 px-5 py-3",
                i < SECTIONS.length - 1 && "border-b border-[var(--border)]/50",
              )}
            >
              <span className="w-28 shrink-0 text-xs font-medium text-[var(--muted-foreground)]">
                {section.label}
              </span>
              <span
                className={cn("font-mono text-sm font-semibold tabular-nums", t?.value)}
              >
                {section.value}
              </span>
              <span
                className={cn(
                  "ml-auto shrink-0 rounded px-2 py-0.5 text-[10px] font-medium",
                  t?.badge,
                )}
              >
                {section.detail}
              </span>
            </div>
          );
        })}
      </div>

      {/* Footer */}
      <div className="border-t border-[var(--border)] bg-[var(--muted)]/30 px-5 py-2.5">
        <p className="text-[10px] text-[var(--muted-foreground)]">
          Generated by WPMgr &bull; Powered by label removable &bull; View in portal
        </p>
      </div>
    </div>
  );
}
